new_string = """
-- BusyUserLog definition

-- Drop table

-- DROP TABLE BusyUserLog;

CREATE TABLE BusyUserLog (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
	UserName text,
	Date  timestamp ,
	WorkedOn smallint DEFAULT 0,
	Type smallint DEFAULT 0,
	LogFor smallint DEFAULT 0,
	S1 text,
	S2 text,
	L1 integer DEFAULT 0,
	L2 integer DEFAULT 0,
	L3 integer DEFAULT 0,
	I1 smallint DEFAULT 0,
	I2 smallint DEFAULT 0,
	I3 smallint DEFAULT 0,
	D1 float DEFAULT 0,
	D2 float DEFAULT 0,
	D3 float DEFAULT 0,
	Description text,
	ComputerName text,
	Particular text,
	companyid integer,
	PRIMARY KEY(companyid, id)
);
CREATE INDEX BUSYUSERLOG_01 ON BusyUserLog (UserName);
CREATE INDEX BUSYUSERLOG_02 ON BusyUserLog (UserName,Date);
CREATE INDEX BUSYUSERLOG_03 ON BusyUserLog (UserName,Date,Type);



-- Company definition

-- Drop table

-- DROP TABLE Company;

CREATE TABLE Company (
    companyid integer generated always as identity primary key,
	Name text,
	PrintName text,
	Address1 text,
	Address2 text,
	Address3 text,
	Address4 text,
	TelNo text,
	Fax text,
	Email text,
	ITPAN text,
	ITWard text,
	LST text,
	CST text,
	ST_37 text,
	STWardNo text,
	ExciseRegNo text,
	ECCCode text,
	PLANo text,
	Range text,
	Division text,
	Collectorate text,
	TINNo text,
	GSTNo text,
	C1 text,
	C2 text,
	OtherDet1 text,
	OtherDet2 text,
	OtherDet3 text,
	TANNo text,
	TDSCaption text,
	TDSCircle text,
	TDSPayerCategory smallint DEFAULT 0,
	PersonName text,
	Designation text,
	PersonPANNo text,
	GuardianName text,
	PersonAddress1 text,
	PersonAddress2 text,
	PersonAddress3 text,
	PersonAddress4 text,
	PersonAddress5 text,
	PersonStateCode smallint DEFAULT 0,
	PersonPinCode text,
	PersonStdCode text,
	PersonPhoneNo text,
	PersonEmail text,
	PersonMobileNo text,
	PersonAltStdCode text,
	PersonAltPhoneNo text,
	PersonAltEmail text,
	TDSAdd1 text,
	TDSAdd2 text,
	TDSAdd3 text,
	TDSAdd4 text,
	TDSAdd5 text,
	TDSStateCode smallint DEFAULT 0,
	TDSPinCode text,
	TDSStdCode text,
	TDSPhoneNo text,
	TDSEmail text,
	TDSAltStdCode text,
	TDSAltPhoneNo text,
	TDSAltEmail text,
	VATPersonName text,
	VATDesignation text,
	VATGuardianName text,
	CreatedOn timestamp ,
	SerialNo text,
	BegFY timestamp ,
	CurFY timestamp ,
	BooksStart timestamp ,
	FreezDate timestamp ,
	ProductName text,
	Major smallint DEFAULT 0,
	Minor smallint DEFAULT 0,
	Revision text,
	STCNo text,
	PremisesCode text,
	TaxableService text,
	STPersonName text,
	STDesignation text,
	STGuardianName text,
	FNIPS boolean DEFAULT false,
	I1 smallint DEFAULT 0,
	FreezeType smallint DEFAULT 0,
	DataFreeze boolean DEFAULT false,
	GUID text,
	DLNo text,
	POSZEROAMTBS boolean DEFAULT false,
	DLNo2 text,
	ShortName text,
	B1 boolean DEFAULT false,
	M1 text,
	CINNo text
);




-- User definition

-- Drop table

-- DROP TABLE User;

CREATE TABLE User (
    companyid integer default 0,
    userid bigint bigint generated always as identity,
    Name text,
    Password text,
    Role text,
    UserName text,
    Email text,
    CreatedOn timestamp,
    LastLogin timestamp,
    primary key (companyid, userid)
);






-- CustomScripts definition

-- Drop table

-- DROP TABLE CustomScripts;

CREATE TABLE CustomScripts (
	RecType smallint DEFAULT 0,
	C1 text,
	M1 text,
	companyid integer,
);
CREATE INDEX CUSTOMSCRIPTS_01 ON CustomScripts (RecType,C1);





-- DbImport definition

-- Drop table

-- DROP TABLE DbImport;

CREATE TABLE DbImport (
	EntityType smallint DEFAULT 0,
	SectionID smallint DEFAULT 0,
	C1 text,
	C2 text,
	C3 text,
	C4 text,
	C5 text,
	B1 boolean DEFAULT false,
	B2 boolean DEFAULT false,
	B3 boolean DEFAULT false,
	B4 boolean DEFAULT false,
	B5 boolean DEFAULT false,
	I1 smallint DEFAULT 0,
	I2 smallint DEFAULT 0,
	I3 smallint DEFAULT 0,
	I4 smallint DEFAULT 0,
	I5 smallint DEFAULT 0,
	L1 integer DEFAULT 0,
	L2 integer DEFAULT 0,
	L3 integer DEFAULT 0,
	L4 integer DEFAULT 0,
	L5 integer DEFAULT 0,
	L6 integer DEFAULT 0,
	L7 integer DEFAULT 0,
	L8 integer DEFAULT 0,
	L9 integer DEFAULT 0,
	L10 integer DEFAULT 0,
	L11 integer DEFAULT 0,
	L12 integer DEFAULT 0,
	L13 integer DEFAULT 0,
	L14 integer DEFAULT 0,
	L15 integer DEFAULT 0,
	M1 text,
	M2 text,
	M3 text,
	M4 text,
	M5 text,
	Date timestamp
);
CREATE INDEX DBIMPORT_01 ON DbImport (C1);





-- FAQDatabase definition

-- Drop table

-- DROP TABLE FAQDatabase;

CREATE TABLE FAQDatabase (
	CallType smallint DEFAULT 0,
	FAQGrpCode integer DEFAULT 0,
	ProblemTitle text,
	Problem text,
	Solution text
);
CREATE INDEX FAQDATABASE_03 ON FAQDatabase (ProblemTitle);




-- FAQGroup definition

-- Drop table

-- DROP TABLE FAQGroup;

CREATE TABLE FAQGroup (
	GrpName text,
	GrpCode integer DEFAULT 0,
	GrpMasterType smallint DEFAULT 0
);
CREATE INDEX FAQGROUP_01 ON FAQGroup (GrpCode,GrpMasterType);




-- FormDetails definition

-- Drop table

-- DROP TABLE FormDetails;

CREATE TABLE FormDetails (
	LanguageID integer DEFAULT 0,
	FormID integer DEFAULT 0,
	FormSubID integer DEFAULT 0,
	FormCaption text,
	FieldID integer DEFAULT 0,
	FieldCaption text
);
CREATE INDEX FORMDETAILS_01 ON FormDetails (LanguageID,FormID,FormSubID);





-- MessageCentre definition

-- Drop table

-- DROP TABLE MessageCentre;

CREATE TABLE MessageCentre (
	VchCode integer DEFAULT 0,
	MsgTo text,
	MsgFrom text,
	Subject text,
	Message text,
	Date1 timestamp ,
	Time1 timestamp ,
	Status smallint DEFAULT 0,
	AckMail boolean DEFAULT false,
	CC text,
	ComputerName text,
	FolderName text,
	MessageType smallint DEFAULT 0,
	BelongTo text,
	Added2Notes boolean DEFAULT false
);
CREATE INDEX MESSAGECENTRE_02 ON MessageCentre (Status);




-- NMCategory definition

-- Drop table

-- DROP TABLE NMCategory;

CREATE TABLE NMCategory (
	UserName text,
	CategoryName text,
	CategoryCode integer DEFAULT 0,
	ParentCategoryCode integer DEFAULT 0
);
CREATE INDEX NMCATEGORY_01 ON NMCategory (UserName,ParentCategoryCode,CategoryCode);
CREATE INDEX NMCATEGORY_02 ON NMCategory (UserName,CategoryCode);





-- NMNotes definition

-- Drop table

-- DROP TABLE NMNotes;

CREATE TABLE NMNotes (
	UserName text,
	NotesCode integer DEFAULT 0,
	NotesText text,
	CategoryCode integer DEFAULT 0,
	SpecifyDeadline boolean DEFAULT false,
	DeadlineDate timestamp ,
	Status smallint DEFAULT 0,
	RemindNote boolean DEFAULT false,
	ReminderOccurence smallint DEFAULT 0,
	Counter integer DEFAULT 0
);
CREATE INDEX NMNOTES_01 ON NMNotes (UserName,DeadlineDate,Status,RemindNote,SpecifyDeadline);
CREATE INDEX NMNOTES_02 ON NMNotes (UserName,CategoryCode);
CREATE INDEX NMNOTES_03 ON NMNotes (UserName,NotesCode);
CREATE INDEX NMNOTES_04 ON NMNotes (UserName,Status,DeadlineDate);




-- OfflineMessage definition

-- Drop table

-- DROP TABLE OfflineMessage;

CREATE TABLE OfflineMessage (
	Code integer DEFAULT 0,
	Type smallint DEFAULT 0,
	UserName text,
	Date1 timestamp ,
	Msg text,
	WorkInBG boolean DEFAULT false,
	CompName text,
	ModeOfSMS smallint DEFAULT 0
);
CREATE INDEX OFFLINEMESSAGE_01 ON OfflineMessage (UserName,Type,WorkInBG);






-- Patches definition

-- Drop table

-- DROP TABLE Patches;

CREATE TABLE Patches (
	DummyFld boolean DEFAULT false,
	MVAction boolean DEFAULT false,
	ShortCut boolean DEFAULT false,
	FinalResults boolean DEFAULT false
);





-- PrinterReps definition

-- Drop table

-- DROP TABLE PrinterReps;

CREATE TABLE PrinterReps (
	RepID smallint DEFAULT 0,
	Name text,
	RepSubID smallint DEFAULT 0,
	ScriptLine text,
	SrNo smallint DEFAULT 0,
	I1 smallint DEFAULT 0,
	I2 smallint DEFAULT 0,
	I3 smallint DEFAULT 0,
	I4 smallint DEFAULT 0,
	I5 smallint DEFAULT 0,
	I6 smallint DEFAULT 0,
	I7 smallint DEFAULT 0,
	I8 smallint DEFAULT 0,
	I9 smallint DEFAULT 0,
	I10 smallint DEFAULT 0,
	I11 smallint DEFAULT 0,
	I12 smallint DEFAULT 0,
	I13 smallint DEFAULT 0,
	I14 smallint DEFAULT 0,
	I15 smallint DEFAULT 0,
	I16 smallint DEFAULT 0,
	I17 smallint DEFAULT 0,
	I18 smallint DEFAULT 0,
	I19 smallint DEFAULT 0,
	I20 smallint DEFAULT 0,
	I21 smallint DEFAULT 0,
	I22 smallint DEFAULT 0,
	I23 smallint DEFAULT 0,
	I24 smallint DEFAULT 0,
	I25 smallint DEFAULT 0,
	I26 smallint DEFAULT 0,
	I27 smallint DEFAULT 0,
	I28 smallint DEFAULT 0,
	I29 smallint DEFAULT 0,
	I30 smallint DEFAULT 0,
	I31 smallint DEFAULT 0,
	I32 smallint DEFAULT 0,
	I33 smallint DEFAULT 0,
	I34 smallint DEFAULT 0,
	I35 smallint DEFAULT 0,
	I36 smallint DEFAULT 0,
	I37 smallint DEFAULT 0,
	I38 smallint DEFAULT 0,
	I39 smallint DEFAULT 0,
	I40 smallint DEFAULT 0,
	B1 boolean DEFAULT false,
	B2 boolean DEFAULT false,
	B3 boolean DEFAULT false,
	B4 boolean DEFAULT false,
	B5 boolean DEFAULT false,
	B6 boolean DEFAULT false,
	B7 boolean DEFAULT false,
	B8 boolean DEFAULT false,
	B9 boolean DEFAULT false,
	B10 boolean DEFAULT false,
	B11 boolean DEFAULT false,
	B12 boolean DEFAULT false,
	B13 boolean DEFAULT false,
	B14 boolean DEFAULT false,
	B15 boolean DEFAULT false,
	B16 boolean DEFAULT false,
	B17 boolean DEFAULT false,
	B18 boolean DEFAULT false,
	B19 boolean DEFAULT false,
	B20 boolean DEFAULT false,
	B21 boolean DEFAULT false,
	B22 boolean DEFAULT false,
	B23 boolean DEFAULT false,
	B24 boolean DEFAULT false,
	B25 boolean DEFAULT false,
	B26 boolean DEFAULT false,
	B27 boolean DEFAULT false,
	B28 boolean DEFAULT false,
	B29 boolean DEFAULT false,
	B30 boolean DEFAULT false,
	B31 boolean DEFAULT false,
	B32 boolean DEFAULT false,
	B33 boolean DEFAULT false,
	B34 boolean DEFAULT false,
	B35 boolean DEFAULT false,
	B36 boolean DEFAULT false,
	B37 boolean DEFAULT false,
	B38 boolean DEFAULT false,
	B39 boolean DEFAULT false,
	B40 boolean DEFAULT false,
	B43 boolean DEFAULT false,
	B44 boolean DEFAULT false,
	B45 boolean DEFAULT false,
	B46 boolean DEFAULT false,
	B47 boolean DEFAULT false,
	B48 boolean DEFAULT false,
	B49 boolean DEFAULT false,
	B50 boolean DEFAULT false,
	B51 boolean DEFAULT false,
	B52 boolean DEFAULT false,
	B53 boolean DEFAULT false,
	B54 boolean DEFAULT false,
	B55 boolean DEFAULT false,
	B56 boolean DEFAULT false,
	B57 boolean DEFAULT false,
	B58 boolean DEFAULT false,
	B59 boolean DEFAULT false,
	B60 boolean DEFAULT false,
	D1 float DEFAULT 0,
	D2 float DEFAULT 0,
	D3 float DEFAULT 0,
	D4 float DEFAULT 0,
	D5 float DEFAULT 0,
	D6 float DEFAULT 0,
	D7 float DEFAULT 0,
	C1 text,
	C2 text,
	C3 text,
	C4 text,
	B41 boolean DEFAULT false,
	B42 boolean DEFAULT false
);
CREATE INDEX PRINTERREPS_01 ON PrinterReps (RepID,RepSubID,Name,SrNo);






-- ScreenReps definition

-- Drop table

-- DROP TABLE ScreenReps;

CREATE TABLE ScreenReps (
	RepID smallint DEFAULT 0,
	Name text,
	RepSubID smallint DEFAULT 0,
	ScriptLine text
);
CREATE INDEX SCREENREPS_01 ON ScreenReps (RepID,RepSubID,Name);




-- SQLQuery definition

-- Drop table

-- DROP TABLE SQLQuery;

CREATE TABLE SQLQuery (
	Code integer DEFAULT 0,
	Name text,
	Query text,
	QueryType smallint DEFAULT 0
);



-- StateCompanyDet definition

-- Drop table

-- DROP TABLE StateCompanyDet;

CREATE TABLE StateCompanyDet (
	StateCode smallint DEFAULT 0,
	Address1 text,
	Address2 text,
	Address3 text,
	Address4 text,
	TIN text,
	GST text,
	CST text,
	TelNo text,
	Fax text,
	Email text,
	ITPAN text,
	ITWard text,
	LST text,
	ST_37 text,
	STWardNo text,
	VATPersonName text,
	VATDesignation text,
	VATGuardianName text,
	ExciseRegNo text,
	ECCCode text,
	PLANo text,
	Range text,
	Division text,
	Collectorate text,
	STRegNo text,
	STCNo text,
	PremisesCode text,
	TaxableService text,
	STPersonName text,
	STDesignation text,
	STGuardianName text,
	PersonName text,
	Designation text,
	GuardianName text,
	PersonAddress1 text,
	PersonAddress2 text,
	PersonAddress3 text,
	PersonAddress4 text,
	PersonAddress5 text,
	PersonStateCode smallint DEFAULT 0,
	PersonPinCode text,
	PersonStdCode text,
	PersonPhoneNo text,
	PersonEmail text,
	TDSAdd1 text,
	TDSAdd2 text,
	TDSAdd3 text,
	TDSAdd4 text,
	TDSAdd5 text,
	TDSStateCode smallint DEFAULT 0,
	TDSPinCode text,
	TDSStdCode text,
	TDSPhoneNo text
);





-- StdNar definition

-- Drop table

-- DROP TABLE StdNar;

CREATE TABLE StdNar (
	VchType smallint DEFAULT 0,
	Narration1 text,
	Narration2 text
);
CREATE INDEX STDNAR_01 ON StdNar (VchType,Narration1,Narration2);




-- UserControl definition

-- Drop table

-- DROP TABLE UserControl;

CREATE TABLE UserControl (
	Name text,
	RecType smallint DEFAULT 0,
	C1 text,
	C2 text,
	C3 text,
	C4 text,
	B1 boolean DEFAULT false,
	B2 boolean DEFAULT false,
	B3 boolean DEFAULT false,
	B4 boolean DEFAULT false,
	B5 boolean DEFAULT false,
	B6 boolean DEFAULT false,
	B7 boolean DEFAULT false,
	B8 boolean DEFAULT false,
	B9 boolean DEFAULT false,
	B10 boolean DEFAULT false,
	B11 boolean DEFAULT false,
	B12 boolean DEFAULT false,
	B13 boolean DEFAULT false,
	B14 boolean DEFAULT false,
	B15 boolean DEFAULT false,
	I1 smallint DEFAULT 0,
	I2 smallint DEFAULT 0,
	I3 smallint DEFAULT 0,
	I4 smallint DEFAULT 0,
	L1 integer DEFAULT 0,
	L2 integer DEFAULT 0,
	L3 integer DEFAULT 0,
	L4 integer DEFAULT 0,
	FinYrs timestamp 
);






-- UserLog definition

-- Drop table

-- DROP TABLE UserLog;

CREATE TABLE UserLog (
	ComputerName text,
	BusyUserName text,
	Date timestamp 
);





-- UserPreferences definition

-- Drop table

-- DROP TABLE UserPreferences;

CREATE TABLE UserPreferences (
    companyid integer DEFAULT 0,
	Name text,
	SuperUser boolean DEFAULT false,
	CanModifyMaster boolean DEFAULT false,
	CanModifyVoucher boolean DEFAULT false,
	CanEditComp boolean DEFAULT false,
	CanBackupComp boolean DEFAULT false,
	CanChangePrice boolean DEFAULT false,
	CanChangeItemWiseDiscount boolean DEFAULT false,
	DosDrvName text,
	WinDrvName text,
	PageLen smallint DEFAULT 0,
	LinesPerPage smallint DEFAULT 0,
	PrintType smallint DEFAULT 0,
	UserPassword text,
	B1 boolean DEFAULT false,
	B2 boolean DEFAULT false,
	B3 boolean DEFAULT false,
	B4 boolean DEFAULT false,
	B5 boolean DEFAULT false,
	B6 boolean DEFAULT false,
	B7 boolean DEFAULT false,
	B8 boolean DEFAULT false,
	B9 boolean DEFAULT false,
	B10 boolean DEFAULT false,
	B11 boolean DEFAULT false,
	B12 boolean DEFAULT false,
	B13 boolean DEFAULT false,
	B14 boolean DEFAULT false,
	B15 boolean DEFAULT false,
	B16 boolean DEFAULT false,
	B17 boolean DEFAULT false,
	B18 boolean DEFAULT false,
	B19 boolean DEFAULT false,
	B20 boolean DEFAULT false,
	B21 boolean DEFAULT false,
	B22 boolean DEFAULT false,
	B23 boolean DEFAULT false,
	B24 boolean DEFAULT false,
	B25 boolean DEFAULT false,
	B26 boolean DEFAULT false,
	B27 boolean DEFAULT false,
	B28 boolean DEFAULT false,
	B29 boolean DEFAULT false,
	B30 boolean DEFAULT false,
	B31 boolean DEFAULT false,
	B32 boolean DEFAULT false,
	B33 boolean DEFAULT false,
	B34 boolean DEFAULT false,
	B35 boolean DEFAULT false,
	B36 boolean DEFAULT false,
	B37 boolean DEFAULT false,
	B38 boolean DEFAULT false,
	B39 boolean DEFAULT false,
	B40 boolean DEFAULT false,
	B41 boolean DEFAULT false,
	B42 boolean DEFAULT false,
	B43 boolean DEFAULT false,
	B44 boolean DEFAULT false,
	B45 boolean DEFAULT false,
	B46 boolean DEFAULT false,
	B47 boolean DEFAULT false,
	B48 boolean DEFAULT false,
	B49 boolean DEFAULT false,
	B50 boolean DEFAULT false,
	B51 boolean DEFAULT false,
	B52 boolean DEFAULT false,
	B53 boolean DEFAULT false,
	B54 boolean DEFAULT false,
	B55 boolean DEFAULT false,
	B56 boolean DEFAULT false,
	B57 boolean DEFAULT false,
	B58 boolean DEFAULT false,
	B59 boolean DEFAULT false,
	B60 boolean DEFAULT false,
	B61 boolean DEFAULT false,
	B62 boolean DEFAULT false,
	B63 boolean DEFAULT false,
	B64 boolean DEFAULT false,
	B65 boolean DEFAULT false,
	B66 boolean DEFAULT false,
	B67 boolean DEFAULT false,
	B68 boolean DEFAULT false,
	B69 boolean DEFAULT false,
	B70 boolean DEFAULT false,
	B71 boolean DEFAULT false,
	B72 boolean DEFAULT false,
	B73 boolean DEFAULT false,
	B74 boolean DEFAULT false,
	B75 boolean DEFAULT false,
	B76 boolean DEFAULT false,
	B77 boolean DEFAULT false,
	B78 boolean DEFAULT false,
	B79 boolean DEFAULT false,
	B80 boolean DEFAULT false,
	B81 boolean DEFAULT false,
	B82 boolean DEFAULT false,
	B83 boolean DEFAULT false,
	B84 boolean DEFAULT false,
	B85 boolean DEFAULT false,
	B86 boolean DEFAULT false,
	B87 boolean DEFAULT false,
	B88 boolean DEFAULT false,
	B89 boolean DEFAULT false,
	B90 boolean DEFAULT false,
	B91 boolean DEFAULT false,
	B92 boolean DEFAULT false,
	B93 boolean DEFAULT false,
	B94 boolean DEFAULT false,
	B95 boolean DEFAULT false,
	B96 boolean DEFAULT false,
	B97 boolean DEFAULT false,
	B98 boolean DEFAULT false,
	B99 boolean DEFAULT false,
	B100 boolean DEFAULT false,
	B101 boolean DEFAULT false,
	B102 boolean DEFAULT false,
	B103 boolean DEFAULT false,
	B104 boolean DEFAULT false,
	B105 boolean DEFAULT false,
	B106 boolean DEFAULT false,
	B107 boolean DEFAULT false,
	B108 boolean DEFAULT false,
	B109 boolean DEFAULT false,
	B110 boolean DEFAULT false,
	B111 boolean DEFAULT false,
	B112 boolean DEFAULT false,
	B113 boolean DEFAULT false,
	B114 boolean DEFAULT false,
	B115 boolean DEFAULT false,
	B116 boolean DEFAULT false,
	B117 boolean DEFAULT false,
	B118 boolean DEFAULT false,
	B119 boolean DEFAULT false,
	B120 boolean DEFAULT false,
	B121 boolean DEFAULT false,
	B122 boolean DEFAULT false,
	B123 boolean DEFAULT false,
	B124 boolean DEFAULT false,
	B125 boolean DEFAULT false,
	B126 boolean DEFAULT false,
	B127 boolean DEFAULT false,
	B128 boolean DEFAULT false,
	B129 boolean DEFAULT false,
	B130 boolean DEFAULT false,
	B131 boolean DEFAULT false,
	B132 boolean DEFAULT false,
	B133 boolean DEFAULT false,
	B134 boolean DEFAULT false,
	B135 boolean DEFAULT false,
	B136 boolean DEFAULT false,
	B137 boolean DEFAULT false,
	B138 boolean DEFAULT false,
	B139 boolean DEFAULT false,
	B140 boolean DEFAULT false,
	B141 boolean DEFAULT false,
	B142 boolean DEFAULT false,
	B143 boolean DEFAULT false,
	B144 boolean DEFAULT false,
	B145 boolean DEFAULT false,
	B146 boolean DEFAULT false,
	B147 boolean DEFAULT false,
	B148 boolean DEFAULT false,
	B149 boolean DEFAULT false,
	B150 boolean DEFAULT false,
	B151 boolean DEFAULT false,
	B152 boolean DEFAULT false,
	B153 boolean DEFAULT false,
	B154 boolean DEFAULT false,
	B155 boolean DEFAULT false,
	B156 boolean DEFAULT false,
	B157 boolean DEFAULT false,
	B158 boolean DEFAULT false,
	B159 boolean DEFAULT false,
	B160 boolean DEFAULT false,
	B161 boolean DEFAULT false,
	B162 boolean DEFAULT false,
	B163 boolean DEFAULT false,
	B164 boolean DEFAULT false,
	B165 boolean DEFAULT false,
	B166 boolean DEFAULT false,
	B167 boolean DEFAULT false,
	B168 boolean DEFAULT false,
	B169 boolean DEFAULT false,
	B170 boolean DEFAULT false,
	B171 boolean DEFAULT false,
	B172 boolean DEFAULT false,
	B173 boolean DEFAULT false,
	B174 boolean DEFAULT false,
	B175 boolean DEFAULT false,
	B176 boolean DEFAULT false,
	B177 boolean DEFAULT false,
	B178 boolean DEFAULT false,
	B179 boolean DEFAULT false,
	B180 boolean DEFAULT false,
	B181 boolean DEFAULT false,
	B182 boolean DEFAULT false,
	B183 boolean DEFAULT false,
	B184 boolean DEFAULT false,
	B185 boolean DEFAULT false,
	B186 boolean DEFAULT false,
	B187 boolean DEFAULT false,
	B188 boolean DEFAULT false,
	B189 boolean DEFAULT false,
	B190 boolean DEFAULT false,
	B191 boolean DEFAULT false,
	B192 boolean DEFAULT false,
	B193 boolean DEFAULT false,
	B194 boolean DEFAULT false,
	B195 boolean DEFAULT false,
	B196 boolean DEFAULT false,
	B197 boolean DEFAULT false,
	B198 boolean DEFAULT false,
	B199 boolean DEFAULT false,
	B200 boolean DEFAULT false,
	PI1 smallint DEFAULT 0,
	PI2 smallint DEFAULT 0,
	PI3 smallint DEFAULT 0,
	PI4 smallint DEFAULT 0,
	PI5 smallint DEFAULT 0,
	PI6 smallint DEFAULT 0,
	PI7 smallint DEFAULT 0,
	PI8 smallint DEFAULT 0,
	PI9 smallint DEFAULT 0,
	PI10 smallint DEFAULT 0,
	PI11 smallint DEFAULT 0,
	PI12 smallint DEFAULT 0,
	PI13 smallint DEFAULT 0,
	PI14 smallint DEFAULT 0,
	PI15 smallint DEFAULT 0,
	PI16 smallint DEFAULT 0,
	PI17 smallint DEFAULT 0,
	PI18 smallint DEFAULT 0,
	PI19 smallint DEFAULT 0,
	PI20 smallint DEFAULT 0,
	L1 integer DEFAULT 0,
	L2 integer DEFAULT 0,
	L3 integer DEFAULT 0,
	L4 integer DEFAULT 0,
	L5 integer DEFAULT 0,
	L6 integer DEFAULT 0,
	L7 integer DEFAULT 0,
	L8 integer DEFAULT 0,
	L9 integer DEFAULT 0,
	L10 integer DEFAULT 0,
	L11 integer DEFAULT 0,
	L12 integer DEFAULT 0,
	L13 integer DEFAULT 0,
	L14 integer DEFAULT 0,
	L15 integer DEFAULT 0,
	L16 integer DEFAULT 0,
	L17 integer DEFAULT 0,
	L18 integer DEFAULT 0,
	L19 integer DEFAULT 0,
	L20 integer DEFAULT 0,
	PI smallint DEFAULT 0,
	primary key (Name, companyid)
);
CREATE INDEX USERPREFERENCES_01 ON UserPreferences (Name);






-- UserPreferences1 definition

-- Drop table

-- DROP TABLE UserPreferences1;

CREATE TABLE UserPreferences1 (
	Name text,
	C1 text,
	C2 text,
	C3 text,
	C4 text,
	C5 text,
	C6 text,
	C7 text,
	C8 text,
	C9 text,
	C10 text,
	C11 text,
	C12 text,
	C13 text,
	C14 text,
	C15 text,
	C16 text,
	C17 text,
	C18 text,
	C19 text,
	C20 text,
	D1 float DEFAULT 0,
	D2 float DEFAULT 0,
	D3 float DEFAULT 0,
	D4 float DEFAULT 0,
	D5 float DEFAULT 0,
	D6 float DEFAULT 0,
	D7 float DEFAULT 0,
	D8 float DEFAULT 0,
	D9 float DEFAULT 0,
	D10 float DEFAULT 0,
	B1 boolean DEFAULT false,
	B2 boolean DEFAULT false,
	B3 boolean DEFAULT false,
	B4 boolean DEFAULT false,
	B5 boolean DEFAULT false,
	B6 boolean DEFAULT false,
	B7 boolean DEFAULT false,
	B8 boolean DEFAULT false,
	B9 boolean DEFAULT false,
	B10 boolean DEFAULT false,
	B11 boolean DEFAULT false,
	B12 boolean DEFAULT false,
	B13 boolean DEFAULT false,
	B14 boolean DEFAULT false,
	B15 boolean DEFAULT false,
	B16 boolean DEFAULT false,
	B17 boolean DEFAULT false,
	B18 boolean DEFAULT false,
	B19 boolean DEFAULT false,
	B20 boolean DEFAULT false,
	B21 boolean DEFAULT false,
	B22 boolean DEFAULT false,
	B23 boolean DEFAULT false,
	B24 boolean DEFAULT false,
	B25 boolean DEFAULT false,
	B26 boolean DEFAULT false,
	B27 boolean DEFAULT false,
	B28 boolean DEFAULT false,
	B29 boolean DEFAULT false,
	B30 boolean DEFAULT false,
	B31 boolean DEFAULT false,
	B32 boolean DEFAULT false,
	B33 boolean DEFAULT false,
	B34 boolean DEFAULT false,
	B35 boolean DEFAULT false,
	B36 boolean DEFAULT false,
	B37 boolean DEFAULT false,
	B38 boolean DEFAULT false,
	B39 boolean DEFAULT false,
	B40 boolean DEFAULT false,
	B41 boolean DEFAULT false,
	B42 boolean DEFAULT false,
	B43 boolean DEFAULT false,
	B44 boolean DEFAULT false,
	B45 boolean DEFAULT false,
	B46 boolean DEFAULT false,
	B47 boolean DEFAULT false,
	B48 boolean DEFAULT false,
	B49 boolean DEFAULT false,
	B50 boolean DEFAULT false,
	B51 boolean DEFAULT false,
	B52 boolean DEFAULT false,
	B53 boolean DEFAULT false,
	B54 boolean DEFAULT false,
	B55 boolean DEFAULT false,
	B56 boolean DEFAULT false,
	B57 boolean DEFAULT false,
	B58 boolean DEFAULT false,
	B59 boolean DEFAULT false,
	B60 boolean DEFAULT false,
	B61 boolean DEFAULT false,
	B62 boolean DEFAULT false,
	B63 boolean DEFAULT false,
	B64 boolean DEFAULT false,
	B65 boolean DEFAULT false,
	B66 boolean DEFAULT false,
	B67 boolean DEFAULT false,
	B68 boolean DEFAULT false,
	B69 boolean DEFAULT false,
	B70 boolean DEFAULT false,
	B71 boolean DEFAULT false,
	B72 boolean DEFAULT false,
	B73 boolean DEFAULT false,
	B74 boolean DEFAULT false,
	B75 boolean DEFAULT false,
	B76 boolean DEFAULT false,
	B77 boolean DEFAULT false,
	B78 boolean DEFAULT false,
	B79 boolean DEFAULT false,
	B80 boolean DEFAULT false,
	B81 boolean DEFAULT false,
	B82 boolean DEFAULT false,
	B83 boolean DEFAULT false,
	B84 boolean DEFAULT false,
	B85 boolean DEFAULT false,
	B86 boolean DEFAULT false,
	B87 boolean DEFAULT false,
	B88 boolean DEFAULT false,
	B89 boolean DEFAULT false,
	B90 boolean DEFAULT false,
	B91 boolean DEFAULT false,
	B92 boolean DEFAULT false,
	B93 boolean DEFAULT false,
	B94 boolean DEFAULT false,
	B95 boolean DEFAULT false,
	B96 boolean DEFAULT false,
	B97 boolean DEFAULT false,
	B98 boolean DEFAULT false,
	B99 boolean DEFAULT false,
	B100 boolean DEFAULT false,
	I1 smallint DEFAULT 0,
	I2 smallint DEFAULT 0,
	I3 smallint DEFAULT 0,
	I4 smallint DEFAULT 0,
	I5 smallint DEFAULT 0,
	I6 smallint DEFAULT 0,
	I7 smallint DEFAULT 0,
	I8 smallint DEFAULT 0,
	I9 smallint DEFAULT 0,
	I10 smallint DEFAULT 0,
	I11 smallint DEFAULT 0,
	I12 smallint DEFAULT 0,
	I13 smallint DEFAULT 0,
	I14 smallint DEFAULT 0,
	I15 smallint DEFAULT 0,
	I16 smallint DEFAULT 0,
	I17 smallint DEFAULT 0,
	I18 smallint DEFAULT 0,
	I19 smallint DEFAULT 0,
	I20 smallint DEFAULT 0,
	L1 integer DEFAULT 0,
	MaintainNM boolean DEFAULT false,
	PopUpNM boolean DEFAULT false,
	LastNMCategoryCode float DEFAULT 0,
	LastNMNotesCode float DEFAULT 0,
	LastThoughtID integer DEFAULT 0,
	MasterVoucherAction text,
	GeneralConfig text,
	PopUpDashBoard boolean DEFAULT false,
	M1 text
);

"""
