import re
from collections import Counter


# convert_string = """
# -- `BusyUserLog` definition
#
# -- Drop table
#
# -- DROP TABLE `BusyUserLog`;
#
# CREATE TABLE `BusyUserLog` (
# 	`UserName` VARCHAR(20),
# 	`Date`  TIMESTAMP DEFAULT '0',
# 	`WorkedOn` SMALLINT DEFAULT 0,
# 	`Type` SMALLINT DEFAULT 0,
# 	`LogFor` SMALLINT DEFAULT 0,
# 	S1 VARCHAR(255),
# 	S2 VARCHAR(255),
# 	L1 INTEGER DEFAULT 0,
# 	L2 INTEGER DEFAULT 0,
# 	L3 INTEGER DEFAULT 0,
# 	I1 SMALLINT DEFAULT 0,
# 	I2 SMALLINT DEFAULT 0,
# 	I3 SMALLINT DEFAULT 0,
# 	D1 DOUBLE DEFAULT 0,
# 	D2 DOUBLE DEFAULT 0,
# 	D3 DOUBLE DEFAULT 0,
# 	`Description` VARCHAR(16777216),
# 	`ComputerName` VARCHAR(40),
# 	`Particular` VARCHAR(255)
# );
# CREATE INDEX BUSYUSERLOG_01 ON `BusyUserLog` (`UserName`);
# CREATE INDEX BUSYUSERLOG_02 ON `BusyUserLog` (`UserName`,`Date`);
# CREATE INDEX BUSYUSERLOG_03 ON `BusyUserLog` (`UserName`,`Date`,`Type`);
#
#
#
# -- `Company` definition
#
# -- Drop table
#
# -- DROP TABLE `Company`;
#
# CREATE TABLE `Company` (
# 	`Name` VARCHAR(40),
# 	`PrintName` VARCHAR(40),
# 	`Address1` VARCHAR(40),
# 	`Address2` VARCHAR(40),
# 	`Address3` VARCHAR(40),
# 	`Address4` VARCHAR(40),
# 	`TelNo` VARCHAR(40),
# 	`Fax` VARCHAR(30),
# 	`Email` VARCHAR(40),
# 	ITPAN VARCHAR(20),
# 	`ITWard` VARCHAR(20),
# 	LST VARCHAR(30),
# 	CST VARCHAR(30),
# 	ST_37 VARCHAR(30),
# 	`STWardNo` VARCHAR(20),
# 	`ExciseRegNo` VARCHAR(30),
# 	`ECCCode` VARCHAR(20),
# 	`PLANo` VARCHAR(20),
# 	`Range` VARCHAR(80),
# 	`Division` VARCHAR(80),
# 	`Collectorate` VARCHAR(40),
# 	`TINNo` VARCHAR(30),
# 	`GSTNo` VARCHAR(30),
# 	C1 VARCHAR(80),
# 	C2 VARCHAR(80),
# 	`OtherDet1` VARCHAR(40),
# 	`OtherDet2` VARCHAR(40),
# 	`OtherDet3` VARCHAR(40),
# 	`TANNo` VARCHAR(40),
# 	`TDSCaption` VARCHAR(40),
# 	`TDSCircle` VARCHAR(40),
# 	`TDSPayerCategory` SMALLINT DEFAULT 0,
# 	`PersonName` VARCHAR(40),
# 	`Designation` VARCHAR(40),
# 	`PersonPANNo` VARCHAR(20),
# 	`GuardianName` VARCHAR(40),
# 	`PersonAddress1` VARCHAR(40),
# 	`PersonAddress2` VARCHAR(40),
# 	`PersonAddress3` VARCHAR(40),
# 	`PersonAddress4` VARCHAR(40),
# 	`PersonAddress5` VARCHAR(40),
# 	`PersonStateCode` SMALLINT DEFAULT 0,
# 	`PersonPinCode` VARCHAR(10),
# 	`PersonStdCode` VARCHAR(10),
# 	`PersonPhoneNo` VARCHAR(40),
# 	`PersonEmail` VARCHAR(40),
# 	`PersonMobileNo` VARCHAR(40),
# 	`PersonAltStdCode` VARCHAR(10),
# 	`PersonAltPhoneNo` VARCHAR(40),
# 	`PersonAltEmail` VARCHAR(40),
# 	`TDSAdd1` VARCHAR(40),
# 	`TDSAdd2` VARCHAR(40),
# 	`TDSAdd3` VARCHAR(40),
# 	`TDSAdd4` VARCHAR(40),
# 	`TDSAdd5` VARCHAR(40),
# 	`TDSStateCode` SMALLINT DEFAULT 0,
# 	`TDSPinCode` VARCHAR(10),
# 	`TDSStdCode` VARCHAR(10),
# 	`TDSPhoneNo` VARCHAR(40),
# 	`TDSEmail` VARCHAR(40),
# 	`TDSAltStdCode` VARCHAR(10),
# 	`TDSAltPhoneNo` VARCHAR(40),
# 	`TDSAltEmail` VARCHAR(40),
# 	`VATPersonName` VARCHAR(40),
# 	`VATDesignation` VARCHAR(40),
# 	`VATGuardianName` VARCHAR(40),
# 	`CreatedOn` TIMESTAMP DEFAULT '0',
# 	`SerialNo` VARCHAR(20),
# 	`BegFY` TIMESTAMP DEFAULT '0',
# 	`CurFY` TIMESTAMP DEFAULT '0',
# 	`BooksStart` TIMESTAMP DEFAULT '0',
# 	`FreezDate` TIMESTAMP DEFAULT '0',
# 	`ProductName` VARCHAR(10),
# 	`Major` SMALLINT DEFAULT 0,
# 	`Minor` SMALLINT DEFAULT 0,
# 	`Revision` VARCHAR(1),
# 	`STCNo` VARCHAR(30),
# 	`PremisesCode` VARCHAR(20),
# 	`TaxableService` VARCHAR(40),
# 	`STPersonName` VARCHAR(40),
# 	`STDesignation` VARCHAR(40),
# 	`STGuardianName` VARCHAR(40),
# 	FNIPS BOOLEAN DEFAULT false,
# 	I1 SMALLINT DEFAULT 0,
# 	`FreezeType` SMALLINT DEFAULT 0,
# 	`DataFreeze` BOOLEAN DEFAULT false,
# 	GUID VARCHAR(40),
# 	`DLNo` VARCHAR(255),
# 	POSZEROAMTBS BOOLEAN DEFAULT false,
# 	`DLNo2` VARCHAR(255),
# 	`ShortName` VARCHAR(10),
# 	B1 BOOLEAN DEFAULT false,
# 	M1 VARCHAR(16777216),
# 	`CINNo` VARCHAR(255)
# );
#
#
#
#
#
#
# -- `CustomScripts` definition
#
# -- Drop table
#
# -- DROP TABLE `CustomScripts`;
#
# CREATE TABLE `CustomScripts` (
# 	`RecType` SMALLINT DEFAULT 0,
# 	C1 VARCHAR(255),
# 	M1 VARCHAR(16777216)
# );
# CREATE INDEX CUSTOMSCRIPTS_01 ON `CustomScripts` (`RecType`,C1);
#
#
#
#
#
# -- `DbImport` definition
#
# -- Drop table
#
# -- DROP TABLE `DbImport`;
#
# CREATE TABLE `DbImport` (
# 	`EntityType` SMALLINT DEFAULT 0,
# 	`SectionID` SMALLINT DEFAULT 0,
# 	C1 VARCHAR(255),
# 	C2 VARCHAR(255),
# 	C3 VARCHAR(255),
# 	C4 VARCHAR(255),
# 	C5 VARCHAR(255),
# 	B1 BOOLEAN DEFAULT false,
# 	B2 BOOLEAN DEFAULT false,
# 	B3 BOOLEAN DEFAULT false,
# 	B4 BOOLEAN DEFAULT false,
# 	B5 BOOLEAN DEFAULT false,
# 	I1 SMALLINT DEFAULT 0,
# 	I2 SMALLINT DEFAULT 0,
# 	I3 SMALLINT DEFAULT 0,
# 	I4 SMALLINT DEFAULT 0,
# 	I5 SMALLINT DEFAULT 0,
# 	L1 INTEGER DEFAULT 0,
# 	L2 INTEGER DEFAULT 0,
# 	L3 INTEGER DEFAULT 0,
# 	L4 INTEGER DEFAULT 0,
# 	L5 INTEGER DEFAULT 0,
# 	L6 INTEGER DEFAULT 0,
# 	L7 INTEGER DEFAULT 0,
# 	L8 INTEGER DEFAULT 0,
# 	L9 INTEGER DEFAULT 0,
# 	L10 INTEGER DEFAULT 0,
# 	L11 INTEGER DEFAULT 0,
# 	L12 INTEGER DEFAULT 0,
# 	L13 INTEGER DEFAULT 0,
# 	L14 INTEGER DEFAULT 0,
# 	L15 INTEGER DEFAULT 0,
# 	M1 VARCHAR(16777216),
# 	M2 VARCHAR(16777216),
# 	M3 VARCHAR(16777216),
# 	M4 VARCHAR(16777216),
# 	M5 VARCHAR(16777216),
# 	`Date` TIMESTAMP DEFAULT '0'
# );
# CREATE INDEX DBIMPORT_01 ON `DbImport` (C1);
#
#
#
#
#
# -- `FAQDatabase` definition
#
# -- Drop table
#
# -- DROP TABLE `FAQDatabase`;
#
# CREATE TABLE `FAQDatabase` (
# 	`CallType` SMALLINT DEFAULT 0,
# 	`FAQGrpCode` INTEGER DEFAULT 0,
# 	`ProblemTitle` VARCHAR(255),
# 	`Problem` VARCHAR(16777216),
# 	`Solution` VARCHAR(16777216)
# );
# CREATE INDEX FAQDATABASE_03 ON `FAQDatabase` (`ProblemTitle`);
#
#
#
#
# -- `FAQGroup` definition
#
# -- Drop table
#
# -- DROP TABLE `FAQGroup`;
#
# CREATE TABLE `FAQGroup` (
# 	`GrpName` VARCHAR(255),
# 	`GrpCode` INTEGER DEFAULT 0,
# 	`GrpMasterType` SMALLINT DEFAULT 0
# );
# CREATE INDEX FAQGROUP_01 ON `FAQGroup` (`GrpCode`,`GrpMasterType`);
#
#
#
#
# -- `FormDetails` definition
#
# -- Drop table
#
# -- DROP TABLE `FormDetails`;
#
# CREATE TABLE `FormDetails` (
# 	`LanguageID` INTEGER DEFAULT 0,
# 	`FormID` INTEGER DEFAULT 0,
# 	`FormSubID` INTEGER DEFAULT 0,
# 	`FormCaption` VARCHAR(255),
# 	`FieldID` INTEGER DEFAULT 0,
# 	`FieldCaption` VARCHAR(255)
# );
# CREATE INDEX FORMDETAILS_01 ON `FormDetails` (`LanguageID`,`FormID`,`FormSubID`);
#
#
#
#
#
# -- `MessageCentre` definition
#
# -- Drop table
#
# -- DROP TABLE `MessageCentre`;
#
# CREATE TABLE `MessageCentre` (
# 	`VchCode` INTEGER DEFAULT 0,
# 	`MsgTo` VARCHAR(16777216),
# 	`MsgFrom` VARCHAR(255),
# 	`Subject` VARCHAR(16777216),
# 	`Message` VARCHAR(16777216),
# 	`Date1` TIMESTAMP DEFAULT '0',
# 	`Time1` TIMESTAMP DEFAULT '0',
# 	`Status` SMALLINT DEFAULT 0,
# 	`AckMail` BOOLEAN DEFAULT false,
# 	CC VARCHAR(16777216),
# 	`ComputerName` VARCHAR(100),
# 	`FolderName` VARCHAR(255),
# 	`MessageType` SMALLINT DEFAULT 0,
# 	`BelongTo` VARCHAR(20),
# 	`Added2Notes` BOOLEAN DEFAULT false
# );
# CREATE INDEX MESSAGECENTRE_02 ON `MessageCentre` (`Status`);
#
#
#
#
# -- `NMCategory` definition
#
# -- Drop table
#
# -- DROP TABLE `NMCategory`;
#
# CREATE TABLE `NMCategory` (
# 	`UserName` VARCHAR(20),
# 	`CategoryName` VARCHAR(255),
# 	`CategoryCode` INTEGER DEFAULT 0,
# 	`ParentCategoryCode` INTEGER DEFAULT 0
# );
# CREATE INDEX NMCATEGORY_01 ON `NMCategory` (`UserName`,`ParentCategoryCode`,`CategoryCode`);
# CREATE INDEX NMCATEGORY_02 ON `NMCategory` (`UserName`,`CategoryCode`);
#
#
#
#
#
# -- `NMNotes` definition
#
# -- Drop table
#
# -- DROP TABLE `NMNotes`;
#
# CREATE TABLE `NMNotes` (
# 	`UserName` VARCHAR(20),
# 	`NotesCode` INTEGER DEFAULT 0,
# 	`NotesText` VARCHAR(16777216),
# 	`CategoryCode` INTEGER DEFAULT 0,
# 	`SpecifyDeadline` BOOLEAN DEFAULT false,
# 	`DeadlineDate` TIMESTAMP DEFAULT '0',
# 	`Status` SMALLINT DEFAULT 0,
# 	`RemindNote` BOOLEAN DEFAULT false,
# 	`ReminderOccurence` SMALLINT DEFAULT 0,
# 	`Counter` INTEGER DEFAULT 0
# );
# CREATE INDEX NMNOTES_01 ON `NMNotes` (`UserName`,`DeadlineDate`,`Status`,`RemindNote`,`SpecifyDeadline`);
# CREATE INDEX NMNOTES_02 ON `NMNotes` (`UserName`,`CategoryCode`);
# CREATE INDEX NMNOTES_03 ON `NMNotes` (`UserName`,`NotesCode`);
# CREATE INDEX NMNOTES_04 ON `NMNotes` (`UserName`,`Status`,`DeadlineDate`);
#
#
#
#
# -- `OfflineMessage` definition
#
# -- Drop table
#
# -- DROP TABLE `OfflineMessage`;
#
# CREATE TABLE `OfflineMessage` (
# 	`Code` INTEGER DEFAULT 0,
# 	`Type` SMALLINT DEFAULT 0,
# 	`UserName` VARCHAR(255),
# 	`Date1` TIMESTAMP DEFAULT '0',
# 	`Msg` VARCHAR(16777216),
# 	`WorkInBG` BOOLEAN DEFAULT false,
# 	`CompName` VARCHAR(255),
# 	`ModeOfSMS` SMALLINT DEFAULT 0
# );
# CREATE INDEX OFFLINEMESSAGE_01 ON `OfflineMessage` (`UserName`,`Type`,`WorkInBG`);
#
#
#
#
#
#
# -- `Patches` definition
#
# -- Drop table
#
# -- DROP TABLE `Patches`;
#
# CREATE TABLE `Patches` (
# 	`DummyFld` BOOLEAN DEFAULT false,
# 	`MVAction` BOOLEAN DEFAULT false,
# 	`ShortCut` BOOLEAN DEFAULT false,
# 	`FinalResults` BOOLEAN DEFAULT false
# );
#
#
#
#
#
# -- `PrinterReps` definition
#
# -- Drop table
#
# -- DROP TABLE `PrinterReps`;
#
# CREATE TABLE `PrinterReps` (
# 	`RepID` SMALLINT DEFAULT 0,
# 	`Name` VARCHAR(20),
# 	`RepSubID` SMALLINT DEFAULT 0,
# 	`ScriptLine` VARCHAR(16777216),
# 	`SrNo` SMALLINT DEFAULT 0,
# 	I1 SMALLINT DEFAULT 0,
# 	I2 SMALLINT DEFAULT 0,
# 	I3 SMALLINT DEFAULT 0,
# 	I4 SMALLINT DEFAULT 0,
# 	I5 SMALLINT DEFAULT 0,
# 	I6 SMALLINT DEFAULT 0,
# 	I7 SMALLINT DEFAULT 0,
# 	I8 SMALLINT DEFAULT 0,
# 	I9 SMALLINT DEFAULT 0,
# 	I10 SMALLINT DEFAULT 0,
# 	I11 SMALLINT DEFAULT 0,
# 	I12 SMALLINT DEFAULT 0,
# 	I13 SMALLINT DEFAULT 0,
# 	I14 SMALLINT DEFAULT 0,
# 	I15 SMALLINT DEFAULT 0,
# 	I16 SMALLINT DEFAULT 0,
# 	I17 SMALLINT DEFAULT 0,
# 	I18 SMALLINT DEFAULT 0,
# 	I19 SMALLINT DEFAULT 0,
# 	I20 SMALLINT DEFAULT 0,
# 	I21 SMALLINT DEFAULT 0,
# 	I22 SMALLINT DEFAULT 0,
# 	I23 SMALLINT DEFAULT 0,
# 	I24 SMALLINT DEFAULT 0,
# 	I25 SMALLINT DEFAULT 0,
# 	I26 SMALLINT DEFAULT 0,
# 	I27 SMALLINT DEFAULT 0,
# 	I28 SMALLINT DEFAULT 0,
# 	I29 SMALLINT DEFAULT 0,
# 	I30 SMALLINT DEFAULT 0,
# 	I31 SMALLINT DEFAULT 0,
# 	I32 SMALLINT DEFAULT 0,
# 	I33 SMALLINT DEFAULT 0,
# 	I34 SMALLINT DEFAULT 0,
# 	I35 SMALLINT DEFAULT 0,
# 	I36 SMALLINT DEFAULT 0,
# 	I37 SMALLINT DEFAULT 0,
# 	I38 SMALLINT DEFAULT 0,
# 	I39 SMALLINT DEFAULT 0,
# 	I40 SMALLINT DEFAULT 0,
# 	B1 BOOLEAN DEFAULT false,
# 	B2 BOOLEAN DEFAULT false,
# 	B3 BOOLEAN DEFAULT false,
# 	B4 BOOLEAN DEFAULT false,
# 	B5 BOOLEAN DEFAULT false,
# 	B6 BOOLEAN DEFAULT false,
# 	B7 BOOLEAN DEFAULT false,
# 	B8 BOOLEAN DEFAULT false,
# 	B9 BOOLEAN DEFAULT false,
# 	B10 BOOLEAN DEFAULT false,
# 	B11 BOOLEAN DEFAULT false,
# 	B12 BOOLEAN DEFAULT false,
# 	B13 BOOLEAN DEFAULT false,
# 	B14 BOOLEAN DEFAULT false,
# 	B15 BOOLEAN DEFAULT false,
# 	B16 BOOLEAN DEFAULT false,
# 	B17 BOOLEAN DEFAULT false,
# 	B18 BOOLEAN DEFAULT false,
# 	B19 BOOLEAN DEFAULT false,
# 	B20 BOOLEAN DEFAULT false,
# 	B21 BOOLEAN DEFAULT false,
# 	B22 BOOLEAN DEFAULT false,
# 	B23 BOOLEAN DEFAULT false,
# 	B24 BOOLEAN DEFAULT false,
# 	B25 BOOLEAN DEFAULT false,
# 	B26 BOOLEAN DEFAULT false,
# 	B27 BOOLEAN DEFAULT false,
# 	B28 BOOLEAN DEFAULT false,
# 	B29 BOOLEAN DEFAULT false,
# 	B30 BOOLEAN DEFAULT false,
# 	B31 BOOLEAN DEFAULT false,
# 	B32 BOOLEAN DEFAULT false,
# 	B33 BOOLEAN DEFAULT false,
# 	B34 BOOLEAN DEFAULT false,
# 	B35 BOOLEAN DEFAULT false,
# 	B36 BOOLEAN DEFAULT false,
# 	B37 BOOLEAN DEFAULT false,
# 	B38 BOOLEAN DEFAULT false,
# 	B39 BOOLEAN DEFAULT false,
# 	B40 BOOLEAN DEFAULT false,
# 	B43 BOOLEAN DEFAULT false,
# 	B44 BOOLEAN DEFAULT false,
# 	B45 BOOLEAN DEFAULT false,
# 	B46 BOOLEAN DEFAULT false,
# 	B47 BOOLEAN DEFAULT false,
# 	B48 BOOLEAN DEFAULT false,
# 	B49 BOOLEAN DEFAULT false,
# 	B50 BOOLEAN DEFAULT false,
# 	B51 BOOLEAN DEFAULT false,
# 	B52 BOOLEAN DEFAULT false,
# 	B53 BOOLEAN DEFAULT false,
# 	B54 BOOLEAN DEFAULT false,
# 	B55 BOOLEAN DEFAULT false,
# 	B56 BOOLEAN DEFAULT false,
# 	B57 BOOLEAN DEFAULT false,
# 	B58 BOOLEAN DEFAULT false,
# 	B59 BOOLEAN DEFAULT false,
# 	B60 BOOLEAN DEFAULT false,
# 	D1 DOUBLE DEFAULT 0,
# 	D2 DOUBLE DEFAULT 0,
# 	D3 DOUBLE DEFAULT 0,
# 	D4 DOUBLE DEFAULT 0,
# 	D5 DOUBLE DEFAULT 0,
# 	D6 DOUBLE DEFAULT 0,
# 	D7 DOUBLE DEFAULT 0,
# 	C1 VARCHAR(20),
# 	C2 VARCHAR(20),
# 	C3 VARCHAR(255),
# 	C4 VARCHAR(255),
# 	B41 BOOLEAN DEFAULT false,
# 	B42 BOOLEAN DEFAULT false
# );
# CREATE INDEX PRINTERREPS_01 ON `PrinterReps` (`RepID`,`RepSubID`,`Name`,`SrNo`);
#
#
#
#
#
#
# -- `ScreenReps` definition
#
# -- Drop table
#
# -- DROP TABLE `ScreenReps`;
#
# CREATE TABLE `ScreenReps` (
# 	`RepID` SMALLINT DEFAULT 0,
# 	`Name` VARCHAR(20),
# 	`RepSubID` SMALLINT DEFAULT 0,
# 	`ScriptLine` VARCHAR(16777216)
# );
# CREATE INDEX SCREENREPS_01 ON `ScreenReps` (`RepID`,`RepSubID`,`Name`);
#
#
#
#
# -- `SQLQuery` definition
#
# -- Drop table
#
# -- DROP TABLE `SQLQuery`;
#
# CREATE TABLE `SQLQuery` (
# 	`Code` INTEGER DEFAULT 0,
# 	`Name` VARCHAR(255),
# 	`Query` VARCHAR(16777216),
# 	`QueryType` SMALLINT DEFAULT 0
# );
#
#
#
# -- `StateCompanyDet` definition
#
# -- Drop table
#
# -- DROP TABLE `StateCompanyDet`;
#
# CREATE TABLE `StateCompanyDet` (
# 	`StateCode` SMALLINT DEFAULT 0,
# 	`Address1` VARCHAR(40),
# 	`Address2` VARCHAR(40),
# 	`Address3` VARCHAR(40),
# 	`Address4` VARCHAR(40),
# 	TIN VARCHAR(30),
# 	GST VARCHAR(30),
# 	CST VARCHAR(30),
# 	`TelNo` VARCHAR(40),
# 	`Fax` VARCHAR(30),
# 	`Email` VARCHAR(40),
# 	ITPAN VARCHAR(20),
# 	`ITWard` VARCHAR(20),
# 	LST VARCHAR(30),
# 	ST_37 VARCHAR(30),
# 	`STWardNo` VARCHAR(20),
# 	`VATPersonName` VARCHAR(40),
# 	`VATDesignation` VARCHAR(40),
# 	`VATGuardianName` VARCHAR(40),
# 	`ExciseRegNo` VARCHAR(30),
# 	`ECCCode` VARCHAR(20),
# 	`PLANo` VARCHAR(20),
# 	`Range` VARCHAR(80),
# 	`Division` VARCHAR(80),
# 	`Collectorate` VARCHAR(40),
# 	`STRegNo` VARCHAR(30),
# 	`STCNo` VARCHAR(30),
# 	`PremisesCode` VARCHAR(20),
# 	`TaxableService` VARCHAR(40),
# 	`STPersonName` VARCHAR(40),
# 	`STDesignation` VARCHAR(40),
# 	`STGuardianName` VARCHAR(40),
# 	`PersonName` VARCHAR(40),
# 	`Designation` VARCHAR(40),
# 	`GuardianName` VARCHAR(40),
# 	`PersonAddress1` VARCHAR(40),
# 	`PersonAddress2` VARCHAR(40),
# 	`PersonAddress3` VARCHAR(40),
# 	`PersonAddress4` VARCHAR(40),
# 	`PersonAddress5` VARCHAR(40),
# 	`PersonStateCode` SMALLINT DEFAULT 0,
# 	`PersonPinCode` VARCHAR(10),
# 	`PersonStdCode` VARCHAR(10),
# 	`PersonPhoneNo` VARCHAR(40),
# 	`PersonEmail` VARCHAR(40),
# 	`TDSAdd1` VARCHAR(40),
# 	`TDSAdd2` VARCHAR(40),
# 	`TDSAdd3` VARCHAR(40),
# 	`TDSAdd4` VARCHAR(40),
# 	`TDSAdd5` VARCHAR(40),
# 	`TDSStateCode` SMALLINT DEFAULT 0,
# 	`TDSPinCode` VARCHAR(10),
# 	`TDSStdCode` VARCHAR(10),
# 	`TDSPhoneNo` VARCHAR(40)
# );
#
#
#
#
#
# -- `StdNar` definition
#
# -- Drop table
#
# -- DROP TABLE `StdNar`;
#
# CREATE TABLE `StdNar` (
# 	`VchType` SMALLINT DEFAULT 0,
# 	`Narration1` VARCHAR(94),
# 	`Narration2` VARCHAR(94)
# );
# CREATE INDEX STDNAR_01 ON `StdNar` (`VchType`,`Narration1`,`Narration2`);
#
#
#
#
# -- `UserControl` definition
#
# -- Drop table
#
# -- DROP TABLE `UserControl`;
#
# CREATE TABLE `UserControl` (
# 	`Name` VARCHAR(20),
# 	`RecType` SMALLINT DEFAULT 0,
# 	C1 VARCHAR(255),
# 	C2 VARCHAR(255),
# 	C3 VARCHAR(255),
# 	C4 VARCHAR(255),
# 	B1 BOOLEAN DEFAULT false,
# 	B2 BOOLEAN DEFAULT false,
# 	B3 BOOLEAN DEFAULT false,
# 	B4 BOOLEAN DEFAULT false,
# 	B5 BOOLEAN DEFAULT false,
# 	B6 BOOLEAN DEFAULT false,
# 	B7 BOOLEAN DEFAULT false,
# 	B8 BOOLEAN DEFAULT false,
# 	B9 BOOLEAN DEFAULT false,
# 	B10 BOOLEAN DEFAULT false,
# 	B11 BOOLEAN DEFAULT false,
# 	B12 BOOLEAN DEFAULT false,
# 	B13 BOOLEAN DEFAULT false,
# 	B14 BOOLEAN DEFAULT false,
# 	B15 BOOLEAN DEFAULT false,
# 	I1 SMALLINT DEFAULT 0,
# 	I2 SMALLINT DEFAULT 0,
# 	I3 SMALLINT DEFAULT 0,
# 	I4 SMALLINT DEFAULT 0,
# 	L1 INTEGER DEFAULT 0,
# 	L2 INTEGER DEFAULT 0,
# 	L3 INTEGER DEFAULT 0,
# 	L4 INTEGER DEFAULT 0,
# 	`FinYrs` TIMESTAMP DEFAULT '0'
# );
#
#
#
#
#
#
# -- `UserLog` definition
#
# -- Drop table
#
# -- DROP TABLE `UserLog`;
#
# CREATE TABLE `UserLog` (
# 	`ComputerName` VARCHAR(255),
# 	`BusyUserName` VARCHAR(255),
# 	`Date` TIMESTAMP DEFAULT '0'
# );
#
#
#
#
#
# -- `UserPreferences` definition
#
# -- Drop table
#
# -- DROP TABLE `UserPreferences`;
#
# CREATE TABLE `UserPreferences` (
# 	`Name` VARCHAR(20),
# 	`SuperUser` BOOLEAN DEFAULT false,
# 	`CanModifyMaster` BOOLEAN DEFAULT false,
# 	`CanModifyVoucher` BOOLEAN DEFAULT false,
# 	`CanEditComp` BOOLEAN DEFAULT false,
# 	`CanBackupComp` BOOLEAN DEFAULT false,
# 	`CanChangePrice` BOOLEAN DEFAULT false,
# 	`CanChangeItemWiseDiscount` BOOLEAN DEFAULT false,
# 	`DosDrvName` VARCHAR(20),
# 	`WinDrvName` VARCHAR(255),
# 	`PageLen` SMALLINT DEFAULT 0,
# 	`LinesPerPage` SMALLINT DEFAULT 0,
# 	`PrintType` SMALLINT DEFAULT 0,
# 	`UserPassword` VARCHAR(100),
# 	B1 BOOLEAN DEFAULT false,
# 	B2 BOOLEAN DEFAULT false,
# 	B3 BOOLEAN DEFAULT false,
# 	B4 BOOLEAN DEFAULT false,
# 	B5 BOOLEAN DEFAULT false,
# 	B6 BOOLEAN DEFAULT false,
# 	B7 BOOLEAN DEFAULT false,
# 	B8 BOOLEAN DEFAULT false,
# 	B9 BOOLEAN DEFAULT false,
# 	B10 BOOLEAN DEFAULT false,
# 	B11 BOOLEAN DEFAULT false,
# 	B12 BOOLEAN DEFAULT false,
# 	B13 BOOLEAN DEFAULT false,
# 	B14 BOOLEAN DEFAULT false,
# 	B15 BOOLEAN DEFAULT false,
# 	B16 BOOLEAN DEFAULT false,
# 	B17 BOOLEAN DEFAULT false,
# 	B18 BOOLEAN DEFAULT false,
# 	B19 BOOLEAN DEFAULT false,
# 	B20 BOOLEAN DEFAULT false,
# 	B21 BOOLEAN DEFAULT false,
# 	B22 BOOLEAN DEFAULT false,
# 	B23 BOOLEAN DEFAULT false,
# 	B24 BOOLEAN DEFAULT false,
# 	B25 BOOLEAN DEFAULT false,
# 	B26 BOOLEAN DEFAULT false,
# 	B27 BOOLEAN DEFAULT false,
# 	B28 BOOLEAN DEFAULT false,
# 	B29 BOOLEAN DEFAULT false,
# 	B30 BOOLEAN DEFAULT false,
# 	B31 BOOLEAN DEFAULT false,
# 	B32 BOOLEAN DEFAULT false,
# 	B33 BOOLEAN DEFAULT false,
# 	B34 BOOLEAN DEFAULT false,
# 	B35 BOOLEAN DEFAULT false,
# 	B36 BOOLEAN DEFAULT false,
# 	B37 BOOLEAN DEFAULT false,
# 	B38 BOOLEAN DEFAULT false,
# 	B39 BOOLEAN DEFAULT false,
# 	B40 BOOLEAN DEFAULT false,
# 	B41 BOOLEAN DEFAULT false,
# 	B42 BOOLEAN DEFAULT false,
# 	B43 BOOLEAN DEFAULT false,
# 	B44 BOOLEAN DEFAULT false,
# 	B45 BOOLEAN DEFAULT false,
# 	B46 BOOLEAN DEFAULT false,
# 	B47 BOOLEAN DEFAULT false,
# 	B48 BOOLEAN DEFAULT false,
# 	B49 BOOLEAN DEFAULT false,
# 	B50 BOOLEAN DEFAULT false,
# 	B51 BOOLEAN DEFAULT false,
# 	B52 BOOLEAN DEFAULT false,
# 	B53 BOOLEAN DEFAULT false,
# 	B54 BOOLEAN DEFAULT false,
# 	B55 BOOLEAN DEFAULT false,
# 	B56 BOOLEAN DEFAULT false,
# 	B57 BOOLEAN DEFAULT false,
# 	B58 BOOLEAN DEFAULT false,
# 	B59 BOOLEAN DEFAULT false,
# 	B60 BOOLEAN DEFAULT false,
# 	B61 BOOLEAN DEFAULT false,
# 	B62 BOOLEAN DEFAULT false,
# 	B63 BOOLEAN DEFAULT false,
# 	B64 BOOLEAN DEFAULT false,
# 	B65 BOOLEAN DEFAULT false,
# 	B66 BOOLEAN DEFAULT false,
# 	B67 BOOLEAN DEFAULT false,
# 	B68 BOOLEAN DEFAULT false,
# 	B69 BOOLEAN DEFAULT false,
# 	B70 BOOLEAN DEFAULT false,
# 	B71 BOOLEAN DEFAULT false,
# 	B72 BOOLEAN DEFAULT false,
# 	B73 BOOLEAN DEFAULT false,
# 	B74 BOOLEAN DEFAULT false,
# 	B75 BOOLEAN DEFAULT false,
# 	B76 BOOLEAN DEFAULT false,
# 	B77 BOOLEAN DEFAULT false,
# 	B78 BOOLEAN DEFAULT false,
# 	B79 BOOLEAN DEFAULT false,
# 	B80 BOOLEAN DEFAULT false,
# 	B81 BOOLEAN DEFAULT false,
# 	B82 BOOLEAN DEFAULT false,
# 	B83 BOOLEAN DEFAULT false,
# 	B84 BOOLEAN DEFAULT false,
# 	B85 BOOLEAN DEFAULT false,
# 	B86 BOOLEAN DEFAULT false,
# 	B87 BOOLEAN DEFAULT false,
# 	B88 BOOLEAN DEFAULT false,
# 	B89 BOOLEAN DEFAULT false,
# 	B90 BOOLEAN DEFAULT false,
# 	B91 BOOLEAN DEFAULT false,
# 	B92 BOOLEAN DEFAULT false,
# 	B93 BOOLEAN DEFAULT false,
# 	B94 BOOLEAN DEFAULT false,
# 	B95 BOOLEAN DEFAULT false,
# 	B96 BOOLEAN DEFAULT false,
# 	B97 BOOLEAN DEFAULT false,
# 	B98 BOOLEAN DEFAULT false,
# 	B99 BOOLEAN DEFAULT false,
# 	B100 BOOLEAN DEFAULT false,
# 	B101 BOOLEAN DEFAULT false,
# 	B102 BOOLEAN DEFAULT false,
# 	B103 BOOLEAN DEFAULT false,
# 	B104 BOOLEAN DEFAULT false,
# 	B105 BOOLEAN DEFAULT false,
# 	B106 BOOLEAN DEFAULT false,
# 	B107 BOOLEAN DEFAULT false,
# 	B108 BOOLEAN DEFAULT false,
# 	B109 BOOLEAN DEFAULT false,
# 	B110 BOOLEAN DEFAULT false,
# 	B111 BOOLEAN DEFAULT false,
# 	B112 BOOLEAN DEFAULT false,
# 	B113 BOOLEAN DEFAULT false,
# 	B114 BOOLEAN DEFAULT false,
# 	B115 BOOLEAN DEFAULT false,
# 	B116 BOOLEAN DEFAULT false,
# 	B117 BOOLEAN DEFAULT false,
# 	B118 BOOLEAN DEFAULT false,
# 	B119 BOOLEAN DEFAULT false,
# 	B120 BOOLEAN DEFAULT false,
# 	B121 BOOLEAN DEFAULT false,
# 	B122 BOOLEAN DEFAULT false,
# 	B123 BOOLEAN DEFAULT false,
# 	B124 BOOLEAN DEFAULT false,
# 	B125 BOOLEAN DEFAULT false,
# 	B126 BOOLEAN DEFAULT false,
# 	B127 BOOLEAN DEFAULT false,
# 	B128 BOOLEAN DEFAULT false,
# 	B129 BOOLEAN DEFAULT false,
# 	B130 BOOLEAN DEFAULT false,
# 	B131 BOOLEAN DEFAULT false,
# 	B132 BOOLEAN DEFAULT false,
# 	B133 BOOLEAN DEFAULT false,
# 	B134 BOOLEAN DEFAULT false,
# 	B135 BOOLEAN DEFAULT false,
# 	B136 BOOLEAN DEFAULT false,
# 	B137 BOOLEAN DEFAULT false,
# 	B138 BOOLEAN DEFAULT false,
# 	B139 BOOLEAN DEFAULT false,
# 	B140 BOOLEAN DEFAULT false,
# 	B141 BOOLEAN DEFAULT false,
# 	B142 BOOLEAN DEFAULT false,
# 	B143 BOOLEAN DEFAULT false,
# 	B144 BOOLEAN DEFAULT false,
# 	B145 BOOLEAN DEFAULT false,
# 	B146 BOOLEAN DEFAULT false,
# 	B147 BOOLEAN DEFAULT false,
# 	B148 BOOLEAN DEFAULT false,
# 	B149 BOOLEAN DEFAULT false,
# 	B150 BOOLEAN DEFAULT false,
# 	B151 BOOLEAN DEFAULT false,
# 	B152 BOOLEAN DEFAULT false,
# 	B153 BOOLEAN DEFAULT false,
# 	B154 BOOLEAN DEFAULT false,
# 	B155 BOOLEAN DEFAULT false,
# 	B156 BOOLEAN DEFAULT false,
# 	B157 BOOLEAN DEFAULT false,
# 	B158 BOOLEAN DEFAULT false,
# 	B159 BOOLEAN DEFAULT false,
# 	B160 BOOLEAN DEFAULT false,
# 	B161 BOOLEAN DEFAULT false,
# 	B162 BOOLEAN DEFAULT false,
# 	B163 BOOLEAN DEFAULT false,
# 	B164 BOOLEAN DEFAULT false,
# 	B165 BOOLEAN DEFAULT false,
# 	B166 BOOLEAN DEFAULT false,
# 	B167 BOOLEAN DEFAULT false,
# 	B168 BOOLEAN DEFAULT false,
# 	B169 BOOLEAN DEFAULT false,
# 	B170 BOOLEAN DEFAULT false,
# 	B171 BOOLEAN DEFAULT false,
# 	B172 BOOLEAN DEFAULT false,
# 	B173 BOOLEAN DEFAULT false,
# 	B174 BOOLEAN DEFAULT false,
# 	B175 BOOLEAN DEFAULT false,
# 	B176 BOOLEAN DEFAULT false,
# 	B177 BOOLEAN DEFAULT false,
# 	B178 BOOLEAN DEFAULT false,
# 	B179 BOOLEAN DEFAULT false,
# 	B180 BOOLEAN DEFAULT false,
# 	B181 BOOLEAN DEFAULT false,
# 	B182 BOOLEAN DEFAULT false,
# 	B183 BOOLEAN DEFAULT false,
# 	B184 BOOLEAN DEFAULT false,
# 	B185 BOOLEAN DEFAULT false,
# 	B186 BOOLEAN DEFAULT false,
# 	B187 BOOLEAN DEFAULT false,
# 	B188 BOOLEAN DEFAULT false,
# 	B189 BOOLEAN DEFAULT false,
# 	B190 BOOLEAN DEFAULT false,
# 	B191 BOOLEAN DEFAULT false,
# 	B192 BOOLEAN DEFAULT false,
# 	B193 BOOLEAN DEFAULT false,
# 	B194 BOOLEAN DEFAULT false,
# 	B195 BOOLEAN DEFAULT false,
# 	B196 BOOLEAN DEFAULT false,
# 	B197 BOOLEAN DEFAULT false,
# 	B198 BOOLEAN DEFAULT false,
# 	B199 BOOLEAN DEFAULT false,
# 	B200 BOOLEAN DEFAULT false,
# 	PI1 SMALLINT DEFAULT 0,
# 	PI2 SMALLINT DEFAULT 0,
# 	PI3 SMALLINT DEFAULT 0,
# 	PI4 SMALLINT DEFAULT 0,
# 	PI5 SMALLINT DEFAULT 0,
# 	PI6 SMALLINT DEFAULT 0,
# 	PI7 SMALLINT DEFAULT 0,
# 	PI8 SMALLINT DEFAULT 0,
# 	PI9 SMALLINT DEFAULT 0,
# 	PI10 SMALLINT DEFAULT 0,
# 	PI11 SMALLINT DEFAULT 0,
# 	PI12 SMALLINT DEFAULT 0,
# 	PI13 SMALLINT DEFAULT 0,
# 	PI14 SMALLINT DEFAULT 0,
# 	PI15 SMALLINT DEFAULT 0,
# 	PI16 SMALLINT DEFAULT 0,
# 	PI17 SMALLINT DEFAULT 0,
# 	PI18 SMALLINT DEFAULT 0,
# 	PI19 SMALLINT DEFAULT 0,
# 	PI20 SMALLINT DEFAULT 0,
# 	L1 INTEGER DEFAULT 0,
# 	L2 INTEGER DEFAULT 0,
# 	L3 INTEGER DEFAULT 0,
# 	L4 INTEGER DEFAULT 0,
# 	L5 INTEGER DEFAULT 0,
# 	L6 INTEGER DEFAULT 0,
# 	L7 INTEGER DEFAULT 0,
# 	L8 INTEGER DEFAULT 0,
# 	L9 INTEGER DEFAULT 0,
# 	L10 INTEGER DEFAULT 0,
# 	L11 INTEGER DEFAULT 0,
# 	L12 INTEGER DEFAULT 0,
# 	L13 INTEGER DEFAULT 0,
# 	L14 INTEGER DEFAULT 0,
# 	L15 INTEGER DEFAULT 0,
# 	L16 INTEGER DEFAULT 0,
# 	L17 INTEGER DEFAULT 0,
# 	L18 INTEGER DEFAULT 0,
# 	L19 INTEGER DEFAULT 0,
# 	L20 INTEGER DEFAULT 0,
# 	PI SMALLINT DEFAULT 0
# );
# CREATE INDEX USERPREFERENCES_01 ON `UserPreferences` (`Name`);
#
#
#
#
#
#
# -- `UserPreferences1` definition
#
# -- Drop table
#
# -- DROP TABLE `UserPreferences1`;
#
# CREATE TABLE `UserPreferences1` (
# 	`Name` VARCHAR(20),
# 	C1 VARCHAR(255),
# 	C2 VARCHAR(255),
# 	C3 VARCHAR(255),
# 	C4 VARCHAR(255),
# 	C5 VARCHAR(255),
# 	C6 VARCHAR(255),
# 	C7 VARCHAR(255),
# 	C8 VARCHAR(255),
# 	C9 VARCHAR(255),
# 	C10 VARCHAR(255),
# 	C11 VARCHAR(255),
# 	C12 VARCHAR(255),
# 	C13 VARCHAR(255),
# 	C14 VARCHAR(255),
# 	C15 VARCHAR(255),
# 	C16 VARCHAR(255),
# 	C17 VARCHAR(255),
# 	C18 VARCHAR(255),
# 	C19 VARCHAR(255),
# 	C20 VARCHAR(255),
# 	D1 DOUBLE DEFAULT 0,
# 	D2 DOUBLE DEFAULT 0,
# 	D3 DOUBLE DEFAULT 0,
# 	D4 DOUBLE DEFAULT 0,
# 	D5 DOUBLE DEFAULT 0,
# 	D6 DOUBLE DEFAULT 0,
# 	D7 DOUBLE DEFAULT 0,
# 	D8 DOUBLE DEFAULT 0,
# 	D9 DOUBLE DEFAULT 0,
# 	D10 DOUBLE DEFAULT 0,
# 	B1 BOOLEAN DEFAULT false,
# 	B2 BOOLEAN DEFAULT false,
# 	B3 BOOLEAN DEFAULT false,
# 	B4 BOOLEAN DEFAULT false,
# 	B5 BOOLEAN DEFAULT false,
# 	B6 BOOLEAN DEFAULT false,
# 	B7 BOOLEAN DEFAULT false,
# 	B8 BOOLEAN DEFAULT false,
# 	B9 BOOLEAN DEFAULT false,
# 	B10 BOOLEAN DEFAULT false,
# 	B11 BOOLEAN DEFAULT false,
# 	B12 BOOLEAN DEFAULT false,
# 	B13 BOOLEAN DEFAULT false,
# 	B14 BOOLEAN DEFAULT false,
# 	B15 BOOLEAN DEFAULT false,
# 	B16 BOOLEAN DEFAULT false,
# 	B17 BOOLEAN DEFAULT false,
# 	B18 BOOLEAN DEFAULT false,
# 	B19 BOOLEAN DEFAULT false,
# 	B20 BOOLEAN DEFAULT false,
# 	B21 BOOLEAN DEFAULT false,
# 	B22 BOOLEAN DEFAULT false,
# 	B23 BOOLEAN DEFAULT false,
# 	B24 BOOLEAN DEFAULT false,
# 	B25 BOOLEAN DEFAULT false,
# 	B26 BOOLEAN DEFAULT false,
# 	B27 BOOLEAN DEFAULT false,
# 	B28 BOOLEAN DEFAULT false,
# 	B29 BOOLEAN DEFAULT false,
# 	B30 BOOLEAN DEFAULT false,
# 	B31 BOOLEAN DEFAULT false,
# 	B32 BOOLEAN DEFAULT false,
# 	B33 BOOLEAN DEFAULT false,
# 	B34 BOOLEAN DEFAULT false,
# 	B35 BOOLEAN DEFAULT false,
# 	B36 BOOLEAN DEFAULT false,
# 	B37 BOOLEAN DEFAULT false,
# 	B38 BOOLEAN DEFAULT false,
# 	B39 BOOLEAN DEFAULT false,
# 	B40 BOOLEAN DEFAULT false,
# 	B41 BOOLEAN DEFAULT false,
# 	B42 BOOLEAN DEFAULT false,
# 	B43 BOOLEAN DEFAULT false,
# 	B44 BOOLEAN DEFAULT false,
# 	B45 BOOLEAN DEFAULT false,
# 	B46 BOOLEAN DEFAULT false,
# 	B47 BOOLEAN DEFAULT false,
# 	B48 BOOLEAN DEFAULT false,
# 	B49 BOOLEAN DEFAULT false,
# 	B50 BOOLEAN DEFAULT false,
# 	B51 BOOLEAN DEFAULT false,
# 	B52 BOOLEAN DEFAULT false,
# 	B53 BOOLEAN DEFAULT false,
# 	B54 BOOLEAN DEFAULT false,
# 	B55 BOOLEAN DEFAULT false,
# 	B56 BOOLEAN DEFAULT false,
# 	B57 BOOLEAN DEFAULT false,
# 	B58 BOOLEAN DEFAULT false,
# 	B59 BOOLEAN DEFAULT false,
# 	B60 BOOLEAN DEFAULT false,
# 	B61 BOOLEAN DEFAULT false,
# 	B62 BOOLEAN DEFAULT false,
# 	B63 BOOLEAN DEFAULT false,
# 	B64 BOOLEAN DEFAULT false,
# 	B65 BOOLEAN DEFAULT false,
# 	B66 BOOLEAN DEFAULT false,
# 	B67 BOOLEAN DEFAULT false,
# 	B68 BOOLEAN DEFAULT false,
# 	B69 BOOLEAN DEFAULT false,
# 	B70 BOOLEAN DEFAULT false,
# 	B71 BOOLEAN DEFAULT false,
# 	B72 BOOLEAN DEFAULT false,
# 	B73 BOOLEAN DEFAULT false,
# 	B74 BOOLEAN DEFAULT false,
# 	B75 BOOLEAN DEFAULT false,
# 	B76 BOOLEAN DEFAULT false,
# 	B77 BOOLEAN DEFAULT false,
# 	B78 BOOLEAN DEFAULT false,
# 	B79 BOOLEAN DEFAULT false,
# 	B80 BOOLEAN DEFAULT false,
# 	B81 BOOLEAN DEFAULT false,
# 	B82 BOOLEAN DEFAULT false,
# 	B83 BOOLEAN DEFAULT false,
# 	B84 BOOLEAN DEFAULT false,
# 	B85 BOOLEAN DEFAULT false,
# 	B86 BOOLEAN DEFAULT false,
# 	B87 BOOLEAN DEFAULT false,
# 	B88 BOOLEAN DEFAULT false,
# 	B89 BOOLEAN DEFAULT false,
# 	B90 BOOLEAN DEFAULT false,
# 	B91 BOOLEAN DEFAULT false,
# 	B92 BOOLEAN DEFAULT false,
# 	B93 BOOLEAN DEFAULT false,
# 	B94 BOOLEAN DEFAULT false,
# 	B95 BOOLEAN DEFAULT false,
# 	B96 BOOLEAN DEFAULT false,
# 	B97 BOOLEAN DEFAULT false,
# 	B98 BOOLEAN DEFAULT false,
# 	B99 BOOLEAN DEFAULT false,
# 	B100 BOOLEAN DEFAULT false,
# 	I1 SMALLINT DEFAULT 0,
# 	I2 SMALLINT DEFAULT 0,
# 	I3 SMALLINT DEFAULT 0,
# 	I4 SMALLINT DEFAULT 0,
# 	I5 SMALLINT DEFAULT 0,
# 	I6 SMALLINT DEFAULT 0,
# 	I7 SMALLINT DEFAULT 0,
# 	I8 SMALLINT DEFAULT 0,
# 	I9 SMALLINT DEFAULT 0,
# 	I10 SMALLINT DEFAULT 0,
# 	I11 SMALLINT DEFAULT 0,
# 	I12 SMALLINT DEFAULT 0,
# 	I13 SMALLINT DEFAULT 0,
# 	I14 SMALLINT DEFAULT 0,
# 	I15 SMALLINT DEFAULT 0,
# 	I16 SMALLINT DEFAULT 0,
# 	I17 SMALLINT DEFAULT 0,
# 	I18 SMALLINT DEFAULT 0,
# 	I19 SMALLINT DEFAULT 0,
# 	I20 SMALLINT DEFAULT 0,
# 	L1 INTEGER DEFAULT 0,
# 	`MaintainNM` BOOLEAN DEFAULT false,
# 	`PopUpNM` BOOLEAN DEFAULT false,
# 	`LastNMCategoryCode` DOUBLE DEFAULT 0,
# 	`LastNMNotesCode` DOUBLE DEFAULT 0,
# 	`LastThoughtID` INTEGER DEFAULT 0,
# 	`MasterVoucherAction` VARCHAR(16777216),
# 	`GeneralConfig` VARCHAR(16777216),
# 	`PopUpDashBoard` BOOLEAN DEFAULT false,
# 	M1 VARCHAR(16777216)
# );
#
# """

convert_string = """-- `AMCWarrDet` definition

-- Drop table

-- DROP TABLE `AMCWarrDet`;

CREATE TABLE `AMCWarrDet` (
	`VchCode` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`Rectype` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`VchNo` VARCHAR(25),
	`RefNo` VARCHAR(25),
	`ItemSerialNo` VARCHAR(255),
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`Value1` DOUBLE DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	`Narration` VARCHAR(255),
	`ContEndDate` TIMESTAMP DEFAULT '0',
	I1 SMALLINT DEFAULT 0,
	`Status` SMALLINT DEFAULT 0
);
CREATE INDEX AMCWARRDET_01 ON `AMCWarrDet` (`MasterCode1`);
CREATE INDEX AMCWARRDET_02 ON `AMCWarrDet` (`MasterCode2`);
CREATE INDEX AMCWARRDET_03 ON `AMCWarrDet` (`ItemSerialNo`);
CREATE INDEX AMCWARRDET_04 ON `AMCWarrDet` (`RefNo`);
CREATE INDEX AMCWARRDET_05 ON `AMCWarrDet` (`ContEndDate`);
CREATE INDEX AMCWARRDET_06 ON `AMCWarrDet` (`VchNo`);
CREATE INDEX AMCWARRDET_07 ON `AMCWarrDet` (`Status`);



-- `BillingDet` definition

-- Drop table

-- DROP TABLE `BillingDet`;

CREATE TABLE `BillingDet` (
	`VchCode` INTEGER DEFAULT 0,
	`PartyName` VARCHAR(40),
	`Address1` VARCHAR(40),
	`Address2` VARCHAR(40),
	`Address3` VARCHAR(40),
	`Address4` VARCHAR(40),
	`STNo` VARCHAR(30),
	`CSTNo` VARCHAR(30),
	`ECCCode` VARCHAR(20),
	`ExciseRegNo` VARCHAR(30),
	`PLANo` VARCHAR(20),
	`Range` VARCHAR(80),
	`Division` VARCHAR(80),
	`Collectorate` VARCHAR(40),
	`MobileNo` VARCHAR(40),
	`Email` VARCHAR(40),
	`DrugLicenceNo1` VARCHAR(40),
	`DrugLicenceNo2` VARCHAR(40),
	ITPAN VARCHAR(20)
);
CREATE INDEX BILLINGDET_01 ON `BillingDet` (`VchCode`);
CREATE INDEX BILLINGDET_02 ON `BillingDet` (`PartyName`);
CREATE INDEX BILLINGDET_03 ON `BillingDet` (`MobileNo`);
CREATE INDEX BILLINGDET_04 ON `BillingDet` (`Email`);




-- `BRSOpBal` definition

-- Drop table

-- DROP TABLE `BRSOpBal`;

CREATE TABLE `BRSOpBal` (
	`SrNo` SMALLINT DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`OpAmt` DOUBLE DEFAULT 0,
	`Type` SMALLINT DEFAULT 0,
	`ShortNar` VARCHAR(40),
	`EntryDate` TIMESTAMP DEFAULT '0',
	`ClrDate` TIMESTAMP DEFAULT '0',
	`OldVchCode` INTEGER DEFAULT 0,
	`VchNo` VARCHAR(25)
);
CREATE INDEX BRSOPBAL_01 ON `BRSOpBal` (`MasterCode1`,`Type`,`SrNo`);
CREATE INDEX BRSOPBAL_02 ON `BRSOpBal` (`MasterCode2`);









-- `CheckList` definition

-- Drop table

-- DROP TABLE `CheckList`;

CREATE TABLE `CheckList` (
	`Type` SMALLINT DEFAULT 0,
	`Code` INTEGER DEFAULT 0,
	`Action` SMALLINT DEFAULT 0,
	`ActionTime` TIMESTAMP DEFAULT '0',
	`UserName` VARCHAR(20),
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	`Notes` VARCHAR(16777216),
	`ComputerName` VARCHAR(25)
);
CREATE INDEX CHECKLIST_21 ON `CheckList` (`Code`);
CREATE INDEX CHECKLIST_23 ON `CheckList` (`UserName`);
CREATE INDEX CHECKLIST_24 ON `CheckList` (`Action`);






-- `Config` definition

-- Drop table

-- DROP TABLE `Config`;

CREATE TABLE `Config` (
	`RecType` SMALLINT DEFAULT 0,
	`Type` SMALLINT DEFAULT 0,
	C1 VARCHAR(20),
	C2 VARCHAR(20),
	C3 VARCHAR(20),
	C4 VARCHAR(20),
	C5 VARCHAR(20),
	C6 VARCHAR(20),
	C7 VARCHAR(20),
	C8 VARCHAR(20),
	C9 VARCHAR(20),
	C10 VARCHAR(20),
	C11 VARCHAR(20),
	C12 VARCHAR(20),
	C13 VARCHAR(20),
	C14 VARCHAR(20),
	C15 VARCHAR(20),
	C16 VARCHAR(20),
	C17 VARCHAR(20),
	C18 VARCHAR(20),
	C19 VARCHAR(20),
	C20 VARCHAR(20),
	C21 VARCHAR(255),
	C22 VARCHAR(255),
	C23 VARCHAR(255),
	C24 VARCHAR(255),
	C25 VARCHAR(255),
	C26 VARCHAR(255),
	C27 VARCHAR(255),
	C28 VARCHAR(255),
	C29 VARCHAR(255),
	C30 VARCHAR(255),
	`DocName` VARCHAR(20),
	`InvVchName` VARCHAR(20),
	`FaVchName` VARCHAR(20),
	I1 SMALLINT DEFAULT 0,
	I2 SMALLINT DEFAULT 0,
	I3 SMALLINT DEFAULT 0,
	I4 SMALLINT DEFAULT 0,
	I5 SMALLINT DEFAULT 0,
	I6 SMALLINT DEFAULT 0,
	I7 SMALLINT DEFAULT 0,
	I8 SMALLINT DEFAULT 0,
	I9 SMALLINT DEFAULT 0,
	I10 SMALLINT DEFAULT 0,
	I11 SMALLINT DEFAULT 0,
	I12 SMALLINT DEFAULT 0,
	I13 SMALLINT DEFAULT 0,
	I14 SMALLINT DEFAULT 0,
	I15 SMALLINT DEFAULT 0,
	I16 SMALLINT DEFAULT 0,
	I17 SMALLINT DEFAULT 0,
	I18 SMALLINT DEFAULT 0,
	I19 SMALLINT DEFAULT 0,
	I20 SMALLINT DEFAULT 0,
	I21 SMALLINT DEFAULT 0,
	I22 SMALLINT DEFAULT 0,
	I23 SMALLINT DEFAULT 0,
	I24 SMALLINT DEFAULT 0,
	I25 SMALLINT DEFAULT 0,
	I26 SMALLINT DEFAULT 0,
	I27 SMALLINT DEFAULT 0,
	I28 SMALLINT DEFAULT 0,
	I29 SMALLINT DEFAULT 0,
	I30 SMALLINT DEFAULT 0,
	I31 SMALLINT DEFAULT 0,
	I32 SMALLINT DEFAULT 0,
	I33 SMALLINT DEFAULT 0,
	I34 SMALLINT DEFAULT 0,
	I35 SMALLINT DEFAULT 0,
	`NoOfFld` SMALLINT DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	B2 BOOLEAN DEFAULT false,
	B3 BOOLEAN DEFAULT false,
	B4 BOOLEAN DEFAULT false,
	B5 BOOLEAN DEFAULT false,
	B6 BOOLEAN DEFAULT false,
	B7 BOOLEAN DEFAULT false,
	B8 BOOLEAN DEFAULT false,
	B9 BOOLEAN DEFAULT false,
	B10 BOOLEAN DEFAULT false,
	B11 BOOLEAN DEFAULT false,
	B12 BOOLEAN DEFAULT false,
	B13 BOOLEAN DEFAULT false,
	B14 BOOLEAN DEFAULT false,
	B15 BOOLEAN DEFAULT false,
	B16 BOOLEAN DEFAULT false,
	B17 BOOLEAN DEFAULT false,
	B18 BOOLEAN DEFAULT false,
	B19 BOOLEAN DEFAULT false,
	B20 BOOLEAN DEFAULT false,
	B21 BOOLEAN DEFAULT false,
	B22 BOOLEAN DEFAULT false,
	B23 BOOLEAN DEFAULT false,
	B24 BOOLEAN DEFAULT false,
	B25 BOOLEAN DEFAULT false,
	B26 BOOLEAN DEFAULT false,
	B27 BOOLEAN DEFAULT false,
	B28 BOOLEAN DEFAULT false,
	B29 BOOLEAN DEFAULT false,
	B30 BOOLEAN DEFAULT false,
	B31 BOOLEAN DEFAULT false,
	B32 BOOLEAN DEFAULT false,
	B33 BOOLEAN DEFAULT false,
	B34 BOOLEAN DEFAULT false,
	B35 BOOLEAN DEFAULT false,
	B36 BOOLEAN DEFAULT false,
	B37 BOOLEAN DEFAULT false,
	B38 BOOLEAN DEFAULT false,
	B39 BOOLEAN DEFAULT false,
	B40 BOOLEAN DEFAULT false,
	B41 BOOLEAN DEFAULT false,
	B42 BOOLEAN DEFAULT false,
	B43 BOOLEAN DEFAULT false,
	B44 BOOLEAN DEFAULT false,
	B45 BOOLEAN DEFAULT false,
	B46 BOOLEAN DEFAULT false,
	B47 BOOLEAN DEFAULT false,
	B48 BOOLEAN DEFAULT false,
	B49 BOOLEAN DEFAULT false,
	B50 BOOLEAN DEFAULT false,
	B51 BOOLEAN DEFAULT false,
	B52 BOOLEAN DEFAULT false,
	B53 BOOLEAN DEFAULT false,
	B54 BOOLEAN DEFAULT false,
	B55 BOOLEAN DEFAULT false,
	B56 BOOLEAN DEFAULT false,
	B57 BOOLEAN DEFAULT false,
	B58 BOOLEAN DEFAULT false,
	B59 BOOLEAN DEFAULT false,
	B60 BOOLEAN DEFAULT false,
	B61 BOOLEAN DEFAULT false,
	B62 BOOLEAN DEFAULT false,
	B63 BOOLEAN DEFAULT false,
	B64 BOOLEAN DEFAULT false,
	B65 BOOLEAN DEFAULT false,
	B66 BOOLEAN DEFAULT false,
	B67 BOOLEAN DEFAULT false,
	B68 BOOLEAN DEFAULT false,
	B69 BOOLEAN DEFAULT false,
	B70 BOOLEAN DEFAULT false,
	B71 BOOLEAN DEFAULT false,
	B72 BOOLEAN DEFAULT false,
	B73 BOOLEAN DEFAULT false,
	B74 BOOLEAN DEFAULT false,
	B75 BOOLEAN DEFAULT false,
	B76 BOOLEAN DEFAULT false,
	B77 BOOLEAN DEFAULT false,
	B78 BOOLEAN DEFAULT false,
	B79 BOOLEAN DEFAULT false,
	B80 BOOLEAN DEFAULT false,
	B81 BOOLEAN DEFAULT false,
	B82 BOOLEAN DEFAULT false,
	B83 BOOLEAN DEFAULT false,
	B84 BOOLEAN DEFAULT false,
	B85 BOOLEAN DEFAULT false,
	B86 BOOLEAN DEFAULT false,
	B87 BOOLEAN DEFAULT false,
	B88 BOOLEAN DEFAULT false,
	B89 BOOLEAN DEFAULT false,
	B90 BOOLEAN DEFAULT false,
	B91 BOOLEAN DEFAULT false,
	B92 BOOLEAN DEFAULT false,
	B93 BOOLEAN DEFAULT false,
	B94 BOOLEAN DEFAULT false,
	B95 BOOLEAN DEFAULT false,
	B96 BOOLEAN DEFAULT false,
	B97 BOOLEAN DEFAULT false,
	B98 BOOLEAN DEFAULT false,
	B99 BOOLEAN DEFAULT false,
	B100 BOOLEAN DEFAULT false,
	B101 BOOLEAN DEFAULT false,
	B102 BOOLEAN DEFAULT false,
	B103 BOOLEAN DEFAULT false,
	B104 BOOLEAN DEFAULT false,
	B105 BOOLEAN DEFAULT false,
	B106 BOOLEAN DEFAULT false,
	B107 BOOLEAN DEFAULT false,
	B108 BOOLEAN DEFAULT false,
	B109 BOOLEAN DEFAULT false,
	B110 BOOLEAN DEFAULT false,
	B111 BOOLEAN DEFAULT false,
	B112 BOOLEAN DEFAULT false,
	B113 BOOLEAN DEFAULT false,
	B114 BOOLEAN DEFAULT false,
	B115 BOOLEAN DEFAULT false,
	B116 BOOLEAN DEFAULT false,
	B117 BOOLEAN DEFAULT false,
	B118 BOOLEAN DEFAULT false,
	B119 BOOLEAN DEFAULT false,
	B120 BOOLEAN DEFAULT false,
	B121 BOOLEAN DEFAULT false,
	B122 BOOLEAN DEFAULT false,
	B123 BOOLEAN DEFAULT false,
	B124 BOOLEAN DEFAULT false,
	B125 BOOLEAN DEFAULT false,
	B126 BOOLEAN DEFAULT false,
	B127 BOOLEAN DEFAULT false,
	B128 BOOLEAN DEFAULT false,
	B129 BOOLEAN DEFAULT false,
	B130 BOOLEAN DEFAULT false,
	B131 BOOLEAN DEFAULT false,
	B132 BOOLEAN DEFAULT false,
	B133 BOOLEAN DEFAULT false,
	B134 BOOLEAN DEFAULT false,
	B135 BOOLEAN DEFAULT false,
	B136 BOOLEAN DEFAULT false,
	B137 BOOLEAN DEFAULT false,
	B138 BOOLEAN DEFAULT false,
	B139 BOOLEAN DEFAULT false,
	B140 BOOLEAN DEFAULT false,
	B141 BOOLEAN DEFAULT false,
	B142 BOOLEAN DEFAULT false,
	L1 INTEGER DEFAULT 0,
	L2 INTEGER DEFAULT 0,
	L3 INTEGER DEFAULT 0,
	L4 INTEGER DEFAULT 0,
	L5 INTEGER DEFAULT 0,
	L6 INTEGER DEFAULT 0,
	L7 INTEGER DEFAULT 0,
	L8 INTEGER DEFAULT 0,
	L9 INTEGER DEFAULT 0,
	L10 INTEGER DEFAULT 0,
	L11 INTEGER DEFAULT 0,
	L12 INTEGER DEFAULT 0,
	L13 INTEGER DEFAULT 0,
	L14 INTEGER DEFAULT 0,
	L15 INTEGER DEFAULT 0,
	L16 INTEGER DEFAULT 0,
	L17 INTEGER DEFAULT 0,
	L18 INTEGER DEFAULT 0,
	L19 INTEGER DEFAULT 0,
	L20 INTEGER DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	D7 DOUBLE DEFAULT 0,
	D8 DOUBLE DEFAULT 0,
	D9 DOUBLE DEFAULT 0,
	D10 DOUBLE DEFAULT 0,
	D11 DOUBLE DEFAULT 0,
	D12 DOUBLE DEFAULT 0,
	D13 DOUBLE DEFAULT 0,
	D14 DOUBLE DEFAULT 0,
	D15 DOUBLE DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	M1 VARCHAR(16777216),
	`PricingMode` SMALLINT DEFAULT 0,
	`PricingModeForPurc` SMALLINT DEFAULT 0,
	M2 VARCHAR(16777216),
	`Stamp` INTEGER DEFAULT 0
);
CREATE INDEX CONFIG_01 ON `Config` (`RecType`,`Type`);
CREATE INDEX CONFIG_02 ON `Config` (`RecType`,L1);
CREATE INDEX CONFIG_03 ON `Config` (CM1);
CREATE INDEX CONFIG_04 ON `Config` (C1);






-- `DailyMessage` definition

-- Drop table

-- DROP TABLE `DailyMessage`;

CREATE TABLE `DailyMessage` (
	`Date` TIMESTAMP DEFAULT '0',
	`NoOfDays` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`VSCode` INTEGER DEFAULT 0,
	`Msg1` VARCHAR(96),
	`Msg2` VARCHAR(96),
	`Msg3` VARCHAR(96),
	`Msg4` VARCHAR(96)
);
CREATE INDEX DAILYMESSAGE_01 ON `DailyMessage` (`Date`,`VchType`,`VSCode`);






-- `DailySum` definition

-- Drop table

-- DROP TABLE `DailySum`;

CREATE TABLE `DailySum` (
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`MasterType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`Dr1` DOUBLE DEFAULT 0,
	`Dr2` DOUBLE DEFAULT 0,
	`Dr3` DOUBLE DEFAULT 0,
	`Cr1` DOUBLE DEFAULT 0,
	`Cr2` DOUBLE DEFAULT 0,
	`Cr3` DOUBLE DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0
);
CREATE INDEX DAILYSUM_11 ON `DailySum` (`MasterCode1`);
CREATE INDEX DAILYSUM_12 ON `DailySum` (`MasterCode2`);
CREATE INDEX DAILYSUM_13 ON `DailySum` (`Date`);







-- `DataSync` definition

-- Drop table

-- DROP TABLE `DataSync`;

CREATE TABLE `DataSync` (
	UID INTEGER DEFAULT 0,
	`BranchCode` INTEGER DEFAULT 0,
	`RecType` SMALLINT DEFAULT 0,
	`Type` SMALLINT DEFAULT 0,
	`VMType` SMALLINT DEFAULT 0,
	`MasterName` VARCHAR(40),
	`VchNo` VARCHAR(25),
	`Date` TIMESTAMP DEFAULT '0',
	`VchSrCode` INTEGER DEFAULT 0,
	`CreatedBy` VARCHAR(20),
	`CreationTime` TIMESTAMP DEFAULT '0',
	`LastModifiedBy` VARCHAR(20),
	`LastModificationTime` TIMESTAMP DEFAULT '0',
	`ApprovedBy` VARCHAR(20),
	`ApprovalTime` TIMESTAMP DEFAULT '0',
	`ServerInTime` TIMESTAMP DEFAULT '0',
	M1 VARCHAR(16777216),
	M2 VARCHAR(16777216),
	`MasterName1` VARCHAR(40),
	`ComputerName` VARCHAR(255),
	`OldVchSrName` VARCHAR(10),
	`OldVchType` SMALLINT DEFAULT 0,
	`VchSrName` VARCHAR(10),
	`DeletedBy` VARCHAR(20),
	`DeletionTime` TIMESTAMP DEFAULT '0',
	`Srno` SMALLINT DEFAULT 0,
	`CheckType` SMALLINT DEFAULT 0,
	`ClearFullVch` BOOLEAN DEFAULT false,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	`OldMasterName` VARCHAR(40),
	`OldDate` TIMESTAMP DEFAULT '0',
	`OldVchNo` VARCHAR(25),
	`OldIdentity` VARCHAR(16777216)
);
CREATE INDEX DATASYNC_01 ON `DataSync` (`BranchCode`,`RecType`,`ServerInTime`);







-- `DeletedInfo` definition

-- Drop table

-- DROP TABLE `DeletedInfo`;

CREATE TABLE `DeletedInfo` (
	`Type` SMALLINT DEFAULT 0,
	`VchMastType` SMALLINT DEFAULT 0,
	`Identity` VARCHAR(50),
	`DeletedBy` VARCHAR(20),
	`DeletionTime` TIMESTAMP DEFAULT '0',
	`OrgVchAmtBaseCur` DOUBLE DEFAULT 0,
	`ModVchAmtBaseCur` DOUBLE DEFAULT 0,
	`ComputerName` VARCHAR(25)
);
CREATE INDEX DELETEDINFO_01 ON `DeletedInfo` (`Type`,`VchMastType`,`DeletionTime`);








-- `EmpLADet` definition

-- Drop table

-- DROP TABLE `EmpLADet`;

CREATE TABLE `EmpLADet` (
	`EmpCode` INTEGER DEFAULT 0,
	`LAType` SMALLINT DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`DueDate` TIMESTAMP DEFAULT '0',
	`Amount` DOUBLE DEFAULT 0,
	`IntAmt` DOUBLE DEFAULT 0,
	`Total` DOUBLE DEFAULT 0,
	`Remarks` VARCHAR(255)
);
CREATE INDEX EMPLADET_01 ON `EmpLADet` (`EmpCode`);
CREATE INDEX EMPLADET_02 ON `EmpLADet` (`LAType`);
CREATE INDEX EMPLADET_03 ON `EmpLADet` (`SrNo`);
CREATE INDEX EMPLADET_04 ON `EmpLADet` (`DueDate`);






-- `EventLog` definition

-- Drop table

-- DROP TABLE `EventLog`;

CREATE TABLE `EventLog` (
	`UserName` VARCHAR(20),
	`Date` TIMESTAMP DEFAULT '0',
	`WorkedOn` SMALLINT DEFAULT 0,
	`Description` VARCHAR(16777216),
	UID INTEGER DEFAULT 0,
	`ComputerName` VARCHAR(40),
	`VersionNo` VARCHAR(40),
	S1 VARCHAR(255),
	`SessionId` INTEGER DEFAULT 0
);
CREATE INDEX EVENTLOG_01 ON `EventLog` (`UserName`);
CREATE INDEX EVENTLOG_02 ON `EventLog` (`Date`);
CREATE INDEX EVENTLOG_03 ON `EventLog` (`WorkedOn`);
CREATE INDEX EVENTLOG_04 ON `EventLog` (UID);
CREATE INDEX EVENTLOG_05 ON `EventLog` (`SessionId`);






-- `Excise` definition

-- Drop table

-- DROP TABLE `Excise`;

CREATE TABLE `Excise` (
	`RecType` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`DocName` VARCHAR(40),
	`VchNo` VARCHAR(25),
	`SrNo` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`Value` DOUBLE DEFAULT 0,
	`Balance` DOUBLE DEFAULT 0,
	`Value1` DOUBLE DEFAULT 0,
	`Balance1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	`Balance2` DOUBLE DEFAULT 0,
	`Value3` DOUBLE DEFAULT 0,
	`Value4` DOUBLE DEFAULT 0,
	`Value5` DOUBLE DEFAULT 0,
	`ValueType` SMALLINT DEFAULT 0,
	`SupplierType` SMALLINT DEFAULT 0,
	`ChallanNo` VARCHAR(40),
	`BankCode` VARCHAR(20),
	`DateOfDeposit` TIMESTAMP DEFAULT '0',
	`PeriodEnding` TIMESTAMP DEFAULT '0',
	`Dummy` SMALLINT DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	`BranchCode` INTEGER DEFAULT 0,
	`ClearanceType` SMALLINT DEFAULT 0,
	`NotificationAvailed` VARCHAR(255),
	`NotificationNo` VARCHAR(255)
);
CREATE INDEX EXCISE_01 ON `Excise` (`RecType`,`VchCode`);
CREATE INDEX EXCISE_02 ON `Excise` (`RecType`,`Date`,`ValueType`,`VchNo`,`VchCode`);







-- `ExternalData` definition

-- Drop table

-- DROP TABLE `ExternalData`;

CREATE TABLE `ExternalData` (
	`KeyType` SMALLINT DEFAULT 0,
	`KeyCode` INTEGER DEFAULT 0,
	`AppName` VARCHAR(20),
	`CanEditKeyData` BOOLEAN DEFAULT false,
	`CanDeleteKeyData` BOOLEAN DEFAULT false,
	I1 SMALLINT DEFAULT 0,
	L1 INTEGER DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	DT1 TIMESTAMP DEFAULT '0',
	C1 VARCHAR(20),
	`Connected` BOOLEAN DEFAULT false,
	`ConnectedCode` INTEGER DEFAULT 0
);
CREATE INDEX EXTERNALDATA_01 ON `ExternalData` (`KeyType`,`KeyCode`);






-- `Folio1` definition

-- Drop table

-- DROP TABLE `Folio1`;

CREATE TABLE `Folio1` (
	`MasterCode` INTEGER DEFAULT 0 NOT NULL,
	`MasterType` SMALLINT DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	D7 DOUBLE DEFAULT 0,
	D8 DOUBLE DEFAULT 0,
	D9 DOUBLE DEFAULT 0,
	D10 DOUBLE DEFAULT 0,
	D11 DOUBLE DEFAULT 0,
	D12 DOUBLE DEFAULT 0,
	D13 DOUBLE DEFAULT 0,
	D14 DOUBLE DEFAULT 0,
	D15 DOUBLE DEFAULT 0,
	D16 DOUBLE DEFAULT 0,
	D17 DOUBLE DEFAULT 0,
	D18 DOUBLE DEFAULT 0,
	D19 DOUBLE DEFAULT 0,
	D20 DOUBLE DEFAULT 0,
	D21 DOUBLE DEFAULT 0,
	D22 DOUBLE DEFAULT 0,
	D23 DOUBLE DEFAULT 0,
	D24 DOUBLE DEFAULT 0,
	D25 DOUBLE DEFAULT 0,
	D26 DOUBLE DEFAULT 0,
	D27 DOUBLE DEFAULT 0,
	D28 DOUBLE DEFAULT 0,
	D29 DOUBLE DEFAULT 0,
	D30 DOUBLE DEFAULT 0,
	D31 DOUBLE DEFAULT 0,
	D32 DOUBLE DEFAULT 0,
	D33 DOUBLE DEFAULT 0,
	D34 DOUBLE DEFAULT 0,
	D35 DOUBLE DEFAULT 0,
	D36 DOUBLE DEFAULT 0,
	D37 DOUBLE DEFAULT 0,
	D38 DOUBLE DEFAULT 0,
	D39 DOUBLE DEFAULT 0,
	D40 DOUBLE DEFAULT 0,
	D41 DOUBLE DEFAULT 0,
	D42 DOUBLE DEFAULT 0,
	D43 DOUBLE DEFAULT 0,
	D44 DOUBLE DEFAULT 0,
	D45 DOUBLE DEFAULT 0,
	D46 DOUBLE DEFAULT 0,
	D47 DOUBLE DEFAULT 0,
	D48 DOUBLE DEFAULT 0,
	D49 DOUBLE DEFAULT 0,
	D50 DOUBLE DEFAULT 0,
	D51 DOUBLE DEFAULT 0,
	D52 DOUBLE DEFAULT 0,
	D53 DOUBLE DEFAULT 0,
	D54 DOUBLE DEFAULT 0,
	D55 DOUBLE DEFAULT 0,
	D56 DOUBLE DEFAULT 0,
	D57 DOUBLE DEFAULT 0,
	D58 DOUBLE DEFAULT 0,
	D59 DOUBLE DEFAULT 0,
	D60 DOUBLE DEFAULT 0,
	D61 DOUBLE DEFAULT 0,
	D62 DOUBLE DEFAULT 0,
	D63 DOUBLE DEFAULT 0,
	D64 DOUBLE DEFAULT 0,
	D65 DOUBLE DEFAULT 0,
	D66 DOUBLE DEFAULT 0,
	D67 DOUBLE DEFAULT 0,
	D68 DOUBLE DEFAULT 0,
	D69 DOUBLE DEFAULT 0,
	D70 DOUBLE DEFAULT 0,
	D71 DOUBLE DEFAULT 0,
	D72 DOUBLE DEFAULT 0,
	D73 DOUBLE DEFAULT 0,
	D74 DOUBLE DEFAULT 0,
	D75 DOUBLE DEFAULT 0,
	D76 DOUBLE DEFAULT 0,
	D77 DOUBLE DEFAULT 0,
	D78 DOUBLE DEFAULT 0,
	D79 DOUBLE DEFAULT 0,
	D80 DOUBLE DEFAULT 0,
	D81 DOUBLE DEFAULT 0,
	D82 DOUBLE DEFAULT 0,
	D83 DOUBLE DEFAULT 0,
	D84 DOUBLE DEFAULT 0,
	D85 DOUBLE DEFAULT 0,
	D86 DOUBLE DEFAULT 0,
	D87 DOUBLE DEFAULT 0,
	D88 DOUBLE DEFAULT 0,
	D89 DOUBLE DEFAULT 0,
	D90 DOUBLE DEFAULT 0,
	D91 DOUBLE DEFAULT 0,
	D92 DOUBLE DEFAULT 0,
	D93 DOUBLE DEFAULT 0,
	D94 DOUBLE DEFAULT 0,
	D95 DOUBLE DEFAULT 0,
	D96 DOUBLE DEFAULT 0,
	D97 DOUBLE DEFAULT 0,
	D98 DOUBLE DEFAULT 0,
	D99 DOUBLE DEFAULT 0,
	D100 DOUBLE DEFAULT 0,
	D101 DOUBLE DEFAULT 0,
	D102 DOUBLE DEFAULT 0,
	D103 DOUBLE DEFAULT 0,
	D104 DOUBLE DEFAULT 0,
	D105 DOUBLE DEFAULT 0,
	D106 DOUBLE DEFAULT 0,
	D107 DOUBLE DEFAULT 0,
	D108 DOUBLE DEFAULT 0,
	D109 DOUBLE DEFAULT 0,
	D110 DOUBLE DEFAULT 0,
	D111 DOUBLE DEFAULT 0,
	D112 DOUBLE DEFAULT 0,
	D113 DOUBLE DEFAULT 0,
	D114 DOUBLE DEFAULT 0,
	D115 DOUBLE DEFAULT 0,
	D116 DOUBLE DEFAULT 0,
	D117 DOUBLE DEFAULT 0,
	D118 DOUBLE DEFAULT 0,
	D119 DOUBLE DEFAULT 0,
	D120 DOUBLE DEFAULT 0,
	D121 DOUBLE DEFAULT 0,
	D122 DOUBLE DEFAULT 0,
	D123 DOUBLE DEFAULT 0,
	D124 DOUBLE DEFAULT 0,
	D125 DOUBLE DEFAULT 0,
	D126 DOUBLE DEFAULT 0,
	D127 DOUBLE DEFAULT 0,
	D128 DOUBLE DEFAULT 0,
	D129 DOUBLE DEFAULT 0,
	D130 DOUBLE DEFAULT 0,
	D131 DOUBLE DEFAULT 0,
	D132 DOUBLE DEFAULT 0,
	D133 DOUBLE DEFAULT 0,
	D134 DOUBLE DEFAULT 0,
	D135 DOUBLE DEFAULT 0,
	D136 DOUBLE DEFAULT 0,
	D137 DOUBLE DEFAULT 0,
	D138 DOUBLE DEFAULT 0,
	D139 DOUBLE DEFAULT 0,
	D140 DOUBLE DEFAULT 0,
	D141 DOUBLE DEFAULT 0,
	D142 DOUBLE DEFAULT 0,
	D143 DOUBLE DEFAULT 0,
	D144 DOUBLE DEFAULT 0,
	D145 DOUBLE DEFAULT 0,
	D146 DOUBLE DEFAULT 0,
	D147 DOUBLE DEFAULT 0,
	D148 DOUBLE DEFAULT 0,
	D149 DOUBLE DEFAULT 0,
	D150 DOUBLE DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	B2 BOOLEAN DEFAULT false,
	B3 BOOLEAN DEFAULT false,
	B4 BOOLEAN DEFAULT false,
	B5 BOOLEAN DEFAULT false,
	B6 BOOLEAN DEFAULT false,
	B7 BOOLEAN DEFAULT false,
	B8 BOOLEAN DEFAULT false,
	B9 BOOLEAN DEFAULT false,
	B10 BOOLEAN DEFAULT false,
	B11 BOOLEAN DEFAULT false,
	B12 BOOLEAN DEFAULT false,
	CONSTRAINT SYS_PK_12184 PRIMARY KEY (`MasterCode`)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12184_12185 ON `Folio1` (`MasterCode`);






-- `Help1` definition

-- Drop table

-- DROP TABLE `Help1`;

CREATE TABLE `Help1` (
	`RecType` SMALLINT DEFAULT 0,
	`NameAlias` VARCHAR(40),
	`Code` INTEGER DEFAULT 0,
	`MasterType` SMALLINT DEFAULT 0,
	`NameOrAlias` SMALLINT DEFAULT 0,
	`AdditionalInfo` VARCHAR(255),
	`ParentGroup` INTEGER DEFAULT 0,
	`MasterSeries` INTEGER DEFAULT 0,
	`Status` SMALLINT DEFAULT 0,
	`DefaultMCCode` INTEGER DEFAULT 0,
	`AddnInfoBt1` VARCHAR(255),
	`AddnInfoBt2` VARCHAR(255),
	`AddnInfoBt3` VARCHAR(255),
	`AddnInfoBt4` VARCHAR(255)
);
CREATE INDEX HELP1_11 ON `Help1` (`MasterSeries`);
CREATE INDEX HELP1_16 ON `Help1` (`RecType`);
CREATE INDEX HELP1_21 ON `Help1` (`Status`);
CREATE INDEX HELP1_26 ON `Help1` (`NameAlias`);
CREATE INDEX HELP1_31 ON `Help1` (`MasterType`);
CREATE INDEX HELP1_36 ON `Help1` (`NameOrAlias`);
CREATE INDEX HELP1_41 ON `Help1` (`Code`);
CREATE INDEX HELP1_46 ON `Help1` (`AdditionalInfo`);
CREATE INDEX HELP1_81 ON `Help1` (`NameOrAlias`,`Code`);
CREATE INDEX HELP1_82 ON `Help1` (`MasterSeries`,`RecType`,`Status`,`NameAlias`);






-- `Help1AddnInfo` definition

-- Drop table

-- DROP TABLE `Help1AddnInfo`;

CREATE TABLE `Help1AddnInfo` (
	`Code` INTEGER DEFAULT 0,
	`AddnInfoBt1` VARCHAR(255),
	`AddnInfoBt2` VARCHAR(255),
	`AddnInfoBt3` VARCHAR(255),
	`AddnInfoBt4` VARCHAR(255)
);
CREATE INDEX HELP1ADDNINFO_21 ON `Help1AddnInfo` (`Code`);





-- `Help2` definition

-- Drop table

-- DROP TABLE `Help2`;

CREATE TABLE `Help2` (
	`RecType1` SMALLINT DEFAULT 0,
	`RecType2` SMALLINT DEFAULT 0,
	`RecType3` INTEGER DEFAULT 0,
	`Name` VARCHAR(40)
);
CREATE INDEX HELP2_01 ON `Help2` (`RecType1`,`RecType2`,`RecType3`,`Name`);






-- `ItemDesc` definition

-- Drop table

-- DROP TABLE `ItemDesc`;

CREATE TABLE `ItemDesc` (
	`VchCode` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`Desc1` VARCHAR(40),
	`Desc2` VARCHAR(40),
	`Desc3` VARCHAR(40),
	`Desc4` VARCHAR(40),
	`Desc5` VARCHAR(40),
	`Desc6` VARCHAR(40),
	`Desc7` VARCHAR(40),
	`Desc8` VARCHAR(40),
	`Desc9` VARCHAR(40),
	`Desc10` VARCHAR(40),
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	I1 SMALLINT DEFAULT 0
);
CREATE INDEX ITEMDESC_01 ON `ItemDesc` (`VchCode`,`SrNo`);





-- `ItemParamDet` definition

-- Drop table

-- DROP TABLE `ItemParamDet`;

CREATE TABLE `ItemParamDet` (
	`Date` TIMESTAMP DEFAULT '0',
	`VchType` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`VchNo` VARCHAR(25),
	`RecType` SMALLINT DEFAULT 0,
	`VchItemSN` SMALLINT DEFAULT 0,
	`ItemCode` INTEGER DEFAULT 0,
	`MCCode` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	C1 VARCHAR(20),
	C2 VARCHAR(20),
	C3 VARCHAR(20),
	C4 VARCHAR(20),
	C5 VARCHAR(20),
	C6 VARCHAR(20),
	C7 VARCHAR(20),
	C8 VARCHAR(20),
	C9 VARCHAR(20),
	C10 VARCHAR(20),
	`Value1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	D7 DOUBLE DEFAULT 0,
	D8 DOUBLE DEFAULT 0,
	D9 DOUBLE DEFAULT 0,
	D10 DOUBLE DEFAULT 0,
	BCN VARCHAR(40),
	`AutoBCN` INTEGER DEFAULT 0,
	`OrgDate` TIMESTAMP DEFAULT '0'
);
CREATE INDEX ITEMPARAMDET_01 ON `ItemParamDet` (`VchCode`,`VchItemSN`,`SrNo`);
CREATE INDEX ITEMPARAMDET_02 ON `ItemParamDet` (`ItemCode`,`MCCode`,`VchCode`,`RecType`,`VchItemSN`,`SrNo`);
CREATE INDEX ITEMPARAMDET_03 ON `ItemParamDet` (`RecType`,`ItemCode`,`MCCode`,`Date`,C1,C2,C3,`Value1`,D3);
CREATE INDEX ITEMPARAMDET_04 ON `ItemParamDet` (BCN);
CREATE INDEX ITEMPARAMDET_06 ON `ItemParamDet` (BCN,`VchCode`);
CREATE INDEX ITEMPARAMDET_07 ON `ItemParamDet` (BCN,`Value1`,`MCCode`);






-- `ItemSerialNo` definition

-- Drop table

-- DROP TABLE `ItemSerialNo`;

CREATE TABLE `ItemSerialNo` (
	`VchCode` INTEGER DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`VchNo` VARCHAR(25),
	`VchItemSN` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`ItemCode` INTEGER DEFAULT 0,
	`MCCode` INTEGER DEFAULT 0,
	`GridSN` INTEGER DEFAULT 0,
	`SerialNo` VARCHAR(255),
	`AutoSrNo` INTEGER DEFAULT 0,
	`Value1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	`MonthVal` SMALLINT DEFAULT 0,
	C1 VARCHAR(40),
	C2 VARCHAR(40),
	C3 VARCHAR(40),
	C4 VARCHAR(40),
	C5 VARCHAR(40),
	C6 VARCHAR(40),
	C7 VARCHAR(40),
	C8 VARCHAR(40),
	C9 VARCHAR(40),
	C10 VARCHAR(40),
	`WarrantyMonth` SMALLINT DEFAULT 0
);
CREATE INDEX ITEMSERIALNO_01 ON `ItemSerialNo` (`ItemCode`,`SerialNo`,`Date`,`VchType`,`VchNo`,`VchCode`);
CREATE INDEX ITEMSERIALNO_02 ON `ItemSerialNo` (`VchCode`,`VchItemSN`,`GridSN`);
CREATE INDEX ITEMSERIALNO_03 ON `ItemSerialNo` (`ItemCode`,`MCCode`,`SerialNo`,`Value1`,`Date`,`VchCode`);
CREATE INDEX ITEMSERIALNO_04 ON `ItemSerialNo` (`ItemCode`,`SerialNo`,`Value1`,`Date`,`VchCode`);
CREATE INDEX ITEMSERIALNO_05 ON `ItemSerialNo` (`ItemCode`,`MCCode`,`VchCode`,`VchItemSN`,`GridSN`,`SerialNo`);
CREATE INDEX ITEMSERIALNO_06 ON `ItemSerialNo` (`ItemCode`,`Value1`,`Date`,`VchType`,`VchCode`,`VchItemSN`,`GridSN`,`SerialNo`);
CREATE INDEX ITEMSERIALNO_07 ON `ItemSerialNo` (`ItemCode`,`VchType`,`VchCode`,`AutoSrNo`);
CREATE INDEX ITEMSERIALNO_08 ON `ItemSerialNo` (`ItemCode`,`MCCode`,`VchCode`,`SerialNo`,`Value1`);
CREATE INDEX ITEMSERIALNO_09 ON `ItemSerialNo` (`ItemCode`,`MCCode`,`SerialNo`,`Value1`);
CREATE INDEX ITEMSERIALNO_10 ON `ItemSerialNo` (`ItemCode`,`AutoSrNo`);
CREATE INDEX ITEMSERIALNO_11 ON `ItemSerialNo` (`ItemCode`,`Date`,`AutoSrNo`);
CREATE INDEX ITEMSERIALNO_12 ON `ItemSerialNo` (`ItemCode`,`MonthVal`,`AutoSrNo`);
CREATE INDEX ITEMSERIALNO_13 ON `ItemSerialNo` (`SerialNo`,`Value1`,`MCCode`);







-- `ItemSNInstallDet` definition

-- Drop table

-- DROP TABLE `ItemSNInstallDet`;

CREATE TABLE `ItemSNInstallDet` (
	`InstallCode` INTEGER DEFAULT 0,
	`InstallDate` TIMESTAMP DEFAULT '0',
	`ItemCode` INTEGER DEFAULT 0,
	`SerialNo` VARCHAR(255),
	`InvoiceNo` VARCHAR(25),
	`InvoiceDate` TIMESTAMP DEFAULT '0',
	`PartyCode` INTEGER DEFAULT 0,
	`Organization` VARCHAR(40),
	`TradeDesc` VARCHAR(40),
	`ContactPerson` VARCHAR(40),
	`Designation` VARCHAR(40),
	`Address1` VARCHAR(40),
	`Address2` VARCHAR(40),
	`CountryCode` INTEGER DEFAULT 0,
	`StateCode` INTEGER DEFAULT 0,
	`CityCode` INTEGER DEFAULT 0,
	`PinCode` VARCHAR(10),
	`MobileNo` VARCHAR(40),
	`PhoneNo` VARCHAR(40),
	`FaxNo` VARCHAR(40),
	`EmailID` VARCHAR(40),
	`Narration` VARCHAR(94),
	`WarrMonth` SMALLINT DEFAULT 0
);
CREATE INDEX ITEMSNINSTALLDET_01 ON `ItemSNInstallDet` (`ItemCode`,`SerialNo`);
CREATE INDEX ITEMSNINSTALLDET_02 ON `ItemSNInstallDet` (`InstallCode`);
CREATE INDEX ITEMSNINSTALLDET_03 ON `ItemSNInstallDet` (`PartyCode`);
CREATE INDEX ITEMSNINSTALLDET_04 ON `ItemSNInstallDet` (`CountryCode`);
CREATE INDEX ITEMSNINSTALLDET_05 ON `ItemSNInstallDet` (`StateCode`);
CREATE INDEX ITEMSNINSTALLDET_06 ON `ItemSNInstallDet` (`CityCode`);





-- `JobFinishedRefs` definition

-- Drop table

-- DROP TABLE `JobFinishedRefs`;

CREATE TABLE `JobFinishedRefs` (
	`JobID` VARCHAR(255),
	`TranType` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`VchNo` VARCHAR(25),
	`VchSeriesCode` INTEGER DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	`Value1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	C1 VARCHAR(255),
	C2 VARCHAR(255),
	C3 VARCHAR(255),
	`Date1` TIMESTAMP DEFAULT '0',
	`Rectype` SMALLINT DEFAULT 0
);
CREATE INDEX JOBFINISHEDREFS_01 ON `JobFinishedRefs` (`MasterCode1`);
CREATE INDEX JOBFINISHEDREFS_02 ON `JobFinishedRefs` (`JobID`);
CREATE INDEX JOBFINISHEDREFS_03 ON `JobFinishedRefs` (`Date`);
CREATE INDEX JOBFINISHEDREFS_04 ON `JobFinishedRefs` (CM1);
CREATE INDEX JOBFINISHEDREFS_05 ON `JobFinishedRefs` (`TranType`);
CREATE INDEX JOBFINISHEDREFS_06 ON `JobFinishedRefs` (`VchType`);
CREATE INDEX JOBFINISHEDREFS_07 ON `JobFinishedRefs` (`MasterCode2`);







-- `Locks` definition

-- Drop table

-- DROP TABLE `Locks`;

CREATE TABLE `Locks` (
	`Type` TIMESTAMP DEFAULT '0',
	IBR BOOLEAN DEFAULT false,
	MBU BOOLEAN DEFAULT false,
	CSU BOOLEAN DEFAULT false,
	STU BOOLEAN DEFAULT false,
	`Working` BOOLEAN DEFAULT false,
	BSSTD BOOLEAN DEFAULT false,
	TERBR BOOLEAN DEFAULT false,
	BRS BOOLEAN DEFAULT false,
	CCCF BOOLEAN DEFAULT false,
	`SuppTypeF` BOOLEAN DEFAULT false,
	BSNF BOOLEAN DEFAULT false,
	BST BOOLEAN DEFAULT false,
	OSPO BOOLEAN DEFAULT false,
	OBAMC BOOLEAN DEFAULT false,
	TDSSHE BOOLEAN DEFAULT false,
	TESRNO BOOLEAN DEFAULT false,
	MAJOR SMALLINT DEFAULT 0,
	MINOR SMALLINT DEFAULT 0,
	RW35 BOOLEAN DEFAULT false,
	MEBR BOOLEAN DEFAULT false,
	MEBR1 BOOLEAN DEFAULT false,
	MFFSA BOOLEAN DEFAULT false,
	SMPL BOOLEAN DEFAULT false,
	GSTU BOOLEAN DEFAULT false,
	MUSPO BOOLEAN DEFAULT false,
	DFYW BOOLEAN DEFAULT false,
	BATCH BOOLEAN DEFAULT false,
	BATCHMRPSRNOPARAM BOOLEAN DEFAULT false,
	ENTRYTAXRATE BOOLEAN DEFAULT false,
	STPTMC BOOLEAN DEFAULT false,
	CHALLANNO BOOLEAN DEFAULT false,
	PARAMDET BOOLEAN DEFAULT false,
	MASTFP BOOLEAN DEFAULT false,
	MASTFP1 BOOLEAN DEFAULT false,
	RMVLOCDB BOOLEAN DEFAULT false,
	POSSERIESFTBSNAME BOOLEAN DEFAULT false,
	STSCGUPDT BOOLEAN DEFAULT false,
	`ItemSrNoLen` BOOLEAN DEFAULT false,
	RGMAST BOOLEAN DEFAULT false,
	`MainDbVer` SMALLINT DEFAULT 0,
	`PartialDbVer` SMALLINT DEFAULT 0,
	COMPEGRPMAST BOOLEAN DEFAULT false,
	COMPCONTGRPMAST BOOLEAN DEFAULT false,
	AREAMAST BOOLEAN DEFAULT false,
	CONTDEPTMAST BOOLEAN DEFAULT false,
	SOURCEMAST BOOLEAN DEFAULT false,
	SUBSTATUSMAST BOOLEAN DEFAULT false,
	NXTACTIONMAST BOOLEAN DEFAULT false,
	TRADEMAST BOOLEAN DEFAULT false,
	B1 BOOLEAN DEFAULT false,
	FAQGRPMAST BOOLEAN DEFAULT false,
	PENDSUBSTATUSMAST BOOLEAN DEFAULT false,
	TRACKINGNO BOOLEAN DEFAULT false,
	`WinUser` VARCHAR(255),
	TOFQ BOOLEAN DEFAULT false,
	`URefBal` BOOLEAN DEFAULT false
);






-- `Master1` definition

-- Drop table

-- DROP TABLE `Master1`;

CREATE TABLE `Master1` (
	`Code` INTEGER DEFAULT 0 NOT NULL,
	`MasterType` SMALLINT DEFAULT 0,
	`Name` VARCHAR(40),
	`Alias` VARCHAR(40),
	`PrintName` VARCHAR(40),
	`ParentGrp` INTEGER DEFAULT 0,
	`Stamp` INTEGER DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	CM2 INTEGER DEFAULT 0,
	CM3 INTEGER DEFAULT 0,
	CM4 INTEGER DEFAULT 0,
	CM5 INTEGER DEFAULT 0,
	CM6 INTEGER DEFAULT 0,
	CM7 INTEGER DEFAULT 0,
	CM8 INTEGER DEFAULT 0,
	CM9 INTEGER DEFAULT 0,
	CM10 INTEGER DEFAULT 0,
	CM11 INTEGER DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	D7 DOUBLE DEFAULT 0,
	D8 DOUBLE DEFAULT 0,
	D9 DOUBLE DEFAULT 0,
	D10 DOUBLE DEFAULT 0,
	D11 DOUBLE DEFAULT 0,
	D12 DOUBLE DEFAULT 0,
	D13 DOUBLE DEFAULT 0,
	D14 DOUBLE DEFAULT 0,
	D15 DOUBLE DEFAULT 0,
	D16 DOUBLE DEFAULT 0,
	D17 DOUBLE DEFAULT 0,
	D18 DOUBLE DEFAULT 0,
	D19 DOUBLE DEFAULT 0,
	D20 DOUBLE DEFAULT 0,
	D21 DOUBLE DEFAULT 0,
	D22 DOUBLE DEFAULT 0,
	D23 DOUBLE DEFAULT 0,
	D24 DOUBLE DEFAULT 0,
	D25 DOUBLE DEFAULT 0,
	I1 SMALLINT DEFAULT 0,
	I2 SMALLINT DEFAULT 0,
	I3 SMALLINT DEFAULT 0,
	I4 SMALLINT DEFAULT 0,
	I5 SMALLINT DEFAULT 0,
	I6 SMALLINT DEFAULT 0,
	I7 SMALLINT DEFAULT 0,
	I8 SMALLINT DEFAULT 0,
	I9 SMALLINT DEFAULT 0,
	I10 SMALLINT DEFAULT 0,
	I11 SMALLINT DEFAULT 0,
	I12 SMALLINT DEFAULT 0,
	I13 SMALLINT DEFAULT 0,
	I14 SMALLINT DEFAULT 0,
	I15 SMALLINT DEFAULT 0,
	I16 SMALLINT DEFAULT 0,
	I17 SMALLINT DEFAULT 0,
	I18 SMALLINT DEFAULT 0,
	I19 SMALLINT DEFAULT 0,
	I20 SMALLINT DEFAULT 0,
	I21 SMALLINT DEFAULT 0,
	I22 SMALLINT DEFAULT 0,
	I23 SMALLINT DEFAULT 0,
	I24 SMALLINT DEFAULT 0,
	`Level` SMALLINT DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	B2 BOOLEAN DEFAULT false,
	B3 BOOLEAN DEFAULT false,
	B4 BOOLEAN DEFAULT false,
	B5 BOOLEAN DEFAULT false,
	B6 BOOLEAN DEFAULT false,
	B7 BOOLEAN DEFAULT false,
	B8 BOOLEAN DEFAULT false,
	B9 BOOLEAN DEFAULT false,
	B10 BOOLEAN DEFAULT false,
	B11 BOOLEAN DEFAULT false,
	B12 BOOLEAN DEFAULT false,
	B13 BOOLEAN DEFAULT false,
	B14 BOOLEAN DEFAULT false,
	B15 BOOLEAN DEFAULT false,
	B16 BOOLEAN DEFAULT false,
	B17 BOOLEAN DEFAULT false,
	B18 BOOLEAN DEFAULT false,
	B19 BOOLEAN DEFAULT false,
	B20 BOOLEAN DEFAULT false,
	B21 BOOLEAN DEFAULT false,
	B22 BOOLEAN DEFAULT false,
	B23 BOOLEAN DEFAULT false,
	B24 BOOLEAN DEFAULT false,
	B25 BOOLEAN DEFAULT false,
	B26 BOOLEAN DEFAULT false,
	B27 BOOLEAN DEFAULT false,
	B28 BOOLEAN DEFAULT false,
	B29 BOOLEAN DEFAULT false,
	B30 BOOLEAN DEFAULT false,
	B31 BOOLEAN DEFAULT false,
	B32 BOOLEAN DEFAULT false,
	B33 BOOLEAN DEFAULT false,
	B34 BOOLEAN DEFAULT false,
	B35 BOOLEAN DEFAULT false,
	B36 BOOLEAN DEFAULT false,
	`External` BOOLEAN DEFAULT false,
	C1 VARCHAR(80),
	C2 VARCHAR(80),
	L1 INTEGER DEFAULT 0,
	L2 INTEGER DEFAULT 0,
	`Notes1` VARCHAR(80),
	`Notes2` VARCHAR(80),
	`MasterNotes` VARCHAR(16777216),
	`CreatedBy` VARCHAR(20),
	`CreationTime` TIMESTAMP DEFAULT '0',
	`ModifiedBy` VARCHAR(20),
	`ModificationTime` TIMESTAMP DEFAULT '0',
	`AuthorisedBy` VARCHAR(20),
	`AuthorisationTime` TIMESTAMP DEFAULT '0',
	`ApprovalStatus` SMALLINT DEFAULT 0,
	`SyncStatus` BOOLEAN DEFAULT false,
	`MasterSeriesGrp` VARCHAR(16777216),
	`Source` SMALLINT DEFAULT 0,
	`BlockedMaster` BOOLEAN DEFAULT false,
	`BlockedNotes` VARCHAR(16777216),
	`DeactiveMaster` BOOLEAN DEFAULT false,
	C3 VARCHAR(255),
	C4 VARCHAR(255),
	`BlockedVchType` VARCHAR(255),
	C5 VARCHAR(255),
	C6 VARCHAR(255),
	M1 VARCHAR(16777216),
	TPF1 BOOLEAN DEFAULT false,
	TPF2 BOOLEAN DEFAULT false,
	`RejectionStatus` SMALLINT DEFAULT 0,
	`OldIdentity` VARCHAR(16777216),
	CONSTRAINT SYS_PK_12189 PRIMARY KEY (`Code`)
);
CREATE INDEX MASTER1_02 ON `Master1` (`MasterType`,`Name`);
CREATE INDEX MASTER1_03 ON `Master1` (`MasterType`,`Alias`);
CREATE INDEX MASTER1_04 ON `Master1` (CM1);
CREATE INDEX MASTER1_05 ON `Master1` (CM2);
CREATE INDEX MASTER1_06 ON `Master1` (CM3);
CREATE INDEX MASTER1_07 ON `Master1` (CM4);
CREATE INDEX MASTER1_08 ON `Master1` (CM5);
CREATE INDEX MASTER1_17 ON `Master1` (CM6);
CREATE INDEX MASTER1_18 ON `Master1` (CM7);
CREATE INDEX MASTER1_20 ON `Master1` (CM8);
CREATE INDEX MASTER1_31 ON `Master1` (`MasterType`);
CREATE INDEX MASTER1_32 ON `Master1` (`Name`);
CREATE INDEX MASTER1_33 ON `Master1` (`Alias`);
CREATE INDEX MASTER1_34 ON `Master1` (`ParentGrp`);
CREATE INDEX MASTER1_35 ON `Master1` (D11);
CREATE INDEX MASTER1_36 ON `Master1` (C2);
CREATE INDEX MASTER1_37 ON `Master1` (`SyncStatus`);
CREATE INDEX MASTER1_38 ON `Master1` (`Source`);
CREATE INDEX MASTER1_39 ON `Master1` (I10);
CREATE INDEX MASTER1_40 ON `Master1` (CM9);
CREATE INDEX MASTER1_41 ON `Master1` (CM10);
CREATE INDEX MASTER1_42 ON `Master1` (CM11);
CREATE INDEX MASTER1_81 ON `Master1` (`Code`);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12189_12190 ON `Master1` (`Code`);






-- `MasterAddressInfo` definition

-- Drop table

-- DROP TABLE `MasterAddressInfo`;

CREATE TABLE `MasterAddressInfo` (
	`MasterCode` INTEGER DEFAULT 0 NOT NULL,
	`Address1` VARCHAR(40),
	`Address2` VARCHAR(40),
	`Address3` VARCHAR(40),
	`Address4` VARCHAR(40),
	`TelNo` VARCHAR(40),
	`Fax` VARCHAR(30),
	`Email` VARCHAR(40),
	`Mobile` VARCHAR(40),
	LST VARCHAR(30),
	CST VARCHAR(30),
	ST37 VARCHAR(30),
	`TINNo` VARCHAR(30),
	`LBTNo` VARCHAR(255),
	ITPAN VARCHAR(20),
	`ITWard` VARCHAR(20),
	`Contact` VARCHAR(40),
	`ExciseRegNo` VARCHAR(30),
	`ECCCode` VARCHAR(20),
	`PLANo` VARCHAR(20),
	`Division` VARCHAR(80),
	`Range` VARCHAR(80),
	`Collectorate` VARCHAR(40),
	OF1 VARCHAR(20),
	OF2 VARCHAR(20),
	OF3 VARCHAR(20),
	OF4 VARCHAR(20),
	OF5 VARCHAR(20),
	OF6 VARCHAR(20),
	OF7 VARCHAR(20),
	OF8 VARCHAR(20),
	OF9 VARCHAR(20),
	OF10 VARCHAR(20),
	`SupplierType` VARCHAR(25),
	`ServiceTaxNo` VARCHAR(30),
	`TelNoResi` VARCHAR(40),
	`GSTNo` VARCHAR(30),
	`CountryCodeLong` INTEGER DEFAULT 0,
	`StateCodeLong` INTEGER DEFAULT 0,
	`CityCodeLong` INTEGER DEFAULT 0,
	`RegionCodeLong` INTEGER DEFAULT 0,
	`AreaCodeLong` INTEGER DEFAULT 0,
	`ContDeptCodeLong` INTEGER DEFAULT 0,
	`PINCode` VARCHAR(10),
	`DLNo` VARCHAR(255),
	`DLNo2` VARCHAR(255),
	`Transport` VARCHAR(30),
	`Station` VARCHAR(30),
	`AccNo` VARCHAR(40),
	`Date1` TIMESTAMP DEFAULT '0',
	`Date2` TIMESTAMP DEFAULT '0',
	`Date3` TIMESTAMP DEFAULT '0',
	`Date4` TIMESTAMP DEFAULT '0',
	`Date5` TIMESTAMP DEFAULT '0',
	`Date6` TIMESTAMP DEFAULT '0',
	`Date7` TIMESTAMP DEFAULT '0',
	`Date8` TIMESTAMP DEFAULT '0',
	C1 VARCHAR(255),
	C2 VARCHAR(255),
	C3 VARCHAR(255),
	C4 VARCHAR(255),
	C5 VARCHAR(255),
	C6 VARCHAR(255),
	C7 VARCHAR(255),
	C8 VARCHAR(255),
	C9 VARCHAR(255),
	C10 VARCHAR(255),
	M1 VARCHAR(16777216),
	CONSTRAINT SYS_PK_12194 PRIMARY KEY (`MasterCode`)
);
CREATE INDEX MASTERADDRESSINFO_02 ON `MasterAddressInfo` (`CountryCodeLong`);
CREATE INDEX MASTERADDRESSINFO_03 ON `MasterAddressInfo` (`StateCodeLong`);
CREATE INDEX MASTERADDRESSINFO_04 ON `MasterAddressInfo` (`CityCodeLong`);
CREATE INDEX MASTERADDRESSINFO_05 ON `MasterAddressInfo` (`RegionCodeLong`);
CREATE INDEX MASTERADDRESSINFO_06 ON `MasterAddressInfo` (`Mobile`);
CREATE INDEX MASTERADDRESSINFO_07 ON `MasterAddressInfo` (`Email`);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12194_12195 ON `MasterAddressInfo` (`MasterCode`);







-- `MasterSupport` definition

-- Drop table

-- DROP TABLE `MasterSupport`;

CREATE TABLE `MasterSupport` (
	`MasterCode` INTEGER DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	CM2 INTEGER DEFAULT 0,
	CM3 INTEGER DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	D7 DOUBLE DEFAULT 0,
	I1 SMALLINT DEFAULT 0,
	I2 SMALLINT DEFAULT 0,
	I3 SMALLINT DEFAULT 0,
	I4 SMALLINT DEFAULT 0,
	I5 SMALLINT DEFAULT 0,
	I6 SMALLINT DEFAULT 0,
	I7 SMALLINT DEFAULT 0,
	I8 SMALLINT DEFAULT 0,
	I9 SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`MasterType` SMALLINT DEFAULT 0,
	C1 VARCHAR(20),
	B1 BOOLEAN DEFAULT false,
	C2 VARCHAR(255),
	C3 VARCHAR(255),
	C4 VARCHAR(255),
	C5 VARCHAR(255),
	B2 BOOLEAN DEFAULT false,
	B3 BOOLEAN DEFAULT false,
	B4 BOOLEAN DEFAULT false,
	D8 DOUBLE DEFAULT 0,
	D9 DOUBLE DEFAULT 0,
	D10 DOUBLE DEFAULT 0,
	D11 DOUBLE DEFAULT 0,
	D12 DOUBLE DEFAULT 0,
	`RecType` SMALLINT DEFAULT 0,
	`Date1` TIMESTAMP DEFAULT '0',
	CM4 INTEGER DEFAULT 0,
	CM5 INTEGER DEFAULT 0,
	`Date2` TIMESTAMP DEFAULT '0',
	`Date3` TIMESTAMP DEFAULT '0',
	M1 VARCHAR(16777216)
);
CREATE INDEX MASTERSUPPORT_03 ON `MasterSupport` (CM2);
CREATE INDEX MASTERSUPPORT_04 ON `MasterSupport` (CM3);
CREATE INDEX MASTERSUPPORT_11 ON `MasterSupport` (`MasterCode`);
CREATE INDEX MASTERSUPPORT_12 ON `MasterSupport` (CM1);
CREATE INDEX MASTERSUPPORT_13 ON `MasterSupport` (`MasterType`);
CREATE INDEX MASTERSUPPORT_14 ON `MasterSupport` (`Date`);
CREATE INDEX MASTERSUPPORT_15 ON `MasterSupport` (I1);
CREATE INDEX MASTERSUPPORT_16 ON `MasterSupport` (I2);
CREATE INDEX MASTERSUPPORT_17 ON `MasterSupport` (C1);
CREATE INDEX MASTERSUPPORT_18 ON `MasterSupport` (`RecType`);
CREATE INDEX MASTERSUPPORT_19 ON `MasterSupport` (`Date1`);
CREATE INDEX MASTERSUPPORT_20 ON `MasterSupport` (CM4);
CREATE INDEX MASTERSUPPORT_21 ON `MasterSupport` (CM5);






-- `MastFootPrint` definition

-- Drop table

-- DROP TABLE `MastFootPrint`;

CREATE TABLE `MastFootPrint` (
	`MasterCode` INTEGER DEFAULT 0,
	`Name` VARCHAR(40),
	`MasterType` SMALLINT DEFAULT 0,
	`Stamp` INTEGER DEFAULT 0,
	`PartialFP` VARCHAR(16777216),
	`RemainFP` VARCHAR(16777216)
);
CREATE INDEX MASTFOOTPRINT_01 ON `MastFootPrint` (`MasterCode`);
CREATE INDEX MASTFOOTPRINT_02 ON `MastFootPrint` (`MasterType`,`Name`);





-- `OEDDet` definition

-- Drop table

-- DROP TABLE `OEDDet`;

CREATE TABLE `OEDDet` (
	`VchCode` INTEGER DEFAULT 0,
	`OEDRate` DOUBLE DEFAULT 0,
	`OEDAmount` DOUBLE DEFAULT 0,
	`CessRate` DOUBLE DEFAULT 0,
	`CessAmount` DOUBLE DEFAULT 0,
	`HECessRate` DOUBLE DEFAULT 0,
	`HECessAmount` DOUBLE DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	I1 SMALLINT DEFAULT 0,
	L1 INTEGER DEFAULT 0
);
CREATE INDEX OEDDET_01 ON `OEDDet` (`VchCode`);






-- `OrgSalePurc` definition

-- Drop table

-- DROP TABLE `OrgSalePurc`;

CREATE TABLE `OrgSalePurc` (
	`VchCode` INTEGER DEFAULT 0,
	`VchNo` VARCHAR(25),
	`VchDate` TIMESTAMP DEFAULT '0',
	`TaxableAmt` DOUBLE DEFAULT 0,
	`TaxAmt` DOUBLE DEFAULT 0,
	`RegType` SMALLINT DEFAULT 0
);
CREATE INDEX ORGSALEPURC_01 ON `OrgSalePurc` (`VchCode`);





-- `PackingDetails` definition

-- Drop table

-- DROP TABLE `PackingDetails`;

CREATE TABLE `PackingDetails` (
	`SrNo` INTEGER DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`PackageNo` VARCHAR(255),
	`Weight` DOUBLE DEFAULT 0,
	`EstimatedValue` DOUBLE DEFAULT 0,
	`Size` VARCHAR(255),
	`Description` VARCHAR(255),
	`Remarks` VARCHAR(255),
	`MarkaNo` VARCHAR(255),
	`Quantity` DOUBLE DEFAULT 0,
	`Unit` INTEGER DEFAULT 0,
	`PackingMode` VARCHAR(255)
);
CREATE INDEX PACKINGDETAILS_01 ON `PackingDetails` (`SrNo`);
CREATE INDEX PACKINGDETAILS_02 ON `PackingDetails` (`PackageNo`);
CREATE INDEX PACKINGDETAILS_03 ON `PackingDetails` (`VchCode`);
CREATE INDEX PACKINGDETAILS_04 ON `PackingDetails` (`Unit`);





-- `Patches` definition

-- Drop table

-- DROP TABLE `Patches`;

CREATE TABLE `Patches` (
	`DummyFld` BOOLEAN DEFAULT false,
	`MasterNotes` BOOLEAN DEFAULT false,
	MBO BOOLEAN DEFAULT false,
	UFSU BOOLEAN DEFAULT false,
	DUFITC BOOLEAN DEFAULT false,
	`CheckList` BOOLEAN DEFAULT false,
	SPACC BOOLEAN DEFAULT false,
	UMBDB1 BOOLEAN DEFAULT false,
	`BCNAltQty` BOOLEAN DEFAULT false,
	UMB1 BOOLEAN DEFAULT false,
	`ExpBatch` BOOLEAN DEFAULT false,
	`QuoteDefaultSeries` BOOLEAN DEFAULT false,
	`BatchStkTfr` BOOLEAN DEFAULT false,
	`ImpactBSSalePurc` BOOLEAN DEFAULT false,
	`DiscMarkupConfig` BOOLEAN DEFAULT false,
	`PickQtnAltQty` BOOLEAN DEFAULT false,
	`VchAudit` BOOLEAN DEFAULT false,
	`DiscHelpData` BOOLEAN DEFAULT false,
	`ItemSrNoLen` BOOLEAN DEFAULT false,
	`SalaryDefaultSeries` BOOLEAN DEFAULT false,
	`FinalResults` BOOLEAN DEFAULT false,
	PDCT3 BOOLEAN DEFAULT false,
	`PaidDays` BOOLEAN DEFAULT false,
	PUSJMC BOOLEAN DEFAULT false,
	`CRSalesDefaultSeries` BOOLEAN DEFAULT false,
	UFRD BOOLEAN DEFAULT false,
	`DefaultSettlementMode` BOOLEAN DEFAULT false,
	`DefaultExciseType` BOOLEAN DEFAULT false,
	`BatchDate` SMALLINT DEFAULT 0,
	`IndentDefaultSeries` BOOLEAN DEFAULT false,
	`UserRights` BOOLEAN DEFAULT false,
	`AccCodes` BOOLEAN DEFAULT false,
	`ItemMastDefaultPrice` BOOLEAN DEFAULT false,
	`ItemMastTreatMRPAsSP` BOOLEAN DEFAULT false,
	`Help1AddnInfo` BOOLEAN DEFAULT false,
	`ItemParamNettAmt` BOOLEAN DEFAULT false,
	`UpgradeForSchemeMast` BOOLEAN DEFAULT false,
	`TEMCWiseRef` BOOLEAN DEFAULT false,
	`SupplierDutyDet` BOOLEAN DEFAULT false
);






-- `PhyStkSubDet` definition

-- Drop table

-- DROP TABLE `PhyStkSubDet`;

CREATE TABLE `PhyStkSubDet` (
	`RecType` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`VchNo` VARCHAR(25),
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`DueDate` TIMESTAMP DEFAULT '0',
	`No` VARCHAR(25),
	`Value1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	`Value3` DOUBLE DEFAULT 0,
	`Balance1` DOUBLE DEFAULT 0,
	`Balance2` DOUBLE DEFAULT 0,
	`Balance3` DOUBLE DEFAULT 0,
	`ItemSrNo` SMALLINT DEFAULT 0,
	`MfgDate` TIMESTAMP DEFAULT '0',
	`NewRefAmount` DOUBLE DEFAULT 0,
	`MonthVal` SMALLINT DEFAULT 0,
	`WarrantyMonth` SMALLINT DEFAULT 0,
	`OrgDate` TIMESTAMP DEFAULT '0',
	C1 VARCHAR(255),
	C2 VARCHAR(255),
	C3 VARCHAR(255),
	C4 VARCHAR(255),
	C5 VARCHAR(255),
	C6 VARCHAR(255),
	C7 VARCHAR(255),
	C8 VARCHAR(255),
	C9 VARCHAR(255),
	C10 VARCHAR(255),
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	B1 BOOLEAN DEFAULT false
);
CREATE INDEX PHYSTKSUBDET_01 ON `PhyStkSubDet` (`MasterCode1`);
CREATE INDEX PHYSTKSUBDET_02 ON `PhyStkSubDet` (`MasterCode2`);
CREATE INDEX PHYSTKSUBDET_03 ON `PhyStkSubDet` (`Date`);
CREATE INDEX PHYSTKSUBDET_04 ON `PhyStkSubDet` (`VchType`);
CREATE INDEX PHYSTKSUBDET_05 ON `PhyStkSubDet` (`VchCode`);
CREATE INDEX PHYSTKSUBDET_06 ON `PhyStkSubDet` (`RecType`);
CREATE INDEX PHYSTKSUBDET_07 ON `PhyStkSubDet` (`SrNo`);
CREATE INDEX PHYSTKSUBDET_08 ON `PhyStkSubDet` (`No`);





-- `POSDet` definition

-- Drop table

-- DROP TABLE `POSDet`;

CREATE TABLE `POSDet` (
	`VchCode` INTEGER DEFAULT 0,
	`CashAmt` DOUBLE DEFAULT 0,
	`ChequeAmt` DOUBLE DEFAULT 0,
	`CCAmt1` DOUBLE DEFAULT 0,
	`CCAmt2` DOUBLE DEFAULT 0,
	`CCAmt3` DOUBLE DEFAULT 0,
	`CashNarr` VARCHAR(40),
	`ChequeNarr` VARCHAR(40),
	`CCNarr1` VARCHAR(40),
	`CCNarr2` VARCHAR(40),
	`CCNarr3` VARCHAR(40),
	`CashRecdAmt` DOUBLE DEFAULT 0,
	`CashAccCode` INTEGER DEFAULT 0,
	`CCAccCode1` INTEGER DEFAULT 0,
	`CCAccCode2` INTEGER DEFAULT 0,
	`CCAccCode3` INTEGER DEFAULT 0,
	`ChequeAccCode` INTEGER DEFAULT 0
);
CREATE INDEX POSDET_01 ON `POSDet` (`VchCode`);





-- `RepColSize` definition

-- Drop table

-- DROP TABLE `RepColSize`;

CREATE TABLE `RepColSize` (
	`RepID` SMALLINT DEFAULT 0,
	`SubID` SMALLINT DEFAULT 0,
	`ColID` SMALLINT DEFAULT 0,
	`ColSize` INTEGER DEFAULT 0,
	`FormatName` VARCHAR(20),
	`CustomRepFormatName` VARCHAR(255),
	`WideScreen` BOOLEAN DEFAULT false
);
CREATE INDEX REPCOLSIZE_01 ON `RepColSize` (`RepID`);
CREATE INDEX REPCOLSIZE_02 ON `RepColSize` (`RepID`,`SubID`);




-- `RepOptValues` definition

-- Drop table

-- DROP TABLE `RepOptValues`;

CREATE TABLE `RepOptValues` (
	`RepID` SMALLINT DEFAULT 0,
	`ReportType` SMALLINT DEFAULT 0,
	`ValueType` SMALLINT DEFAULT 0,
	`Value` VARCHAR(255),
	`MasterType` SMALLINT DEFAULT 0,
	`FieldID` SMALLINT DEFAULT 0,
	`FieldValue` VARCHAR(16777216),
	`SubRepID` SMALLINT DEFAULT 0,
	`FormatName` VARCHAR(40)
);
CREATE INDEX REPOPTVALUES_01 ON `RepOptValues` (`RepID`,`ReportType`);





-- `STDet` definition

-- Drop table

-- DROP TABLE `STDet`;

CREATE TABLE `STDet` (
	`VchCode` INTEGER DEFAULT 0,
	`STCategory` SMALLINT DEFAULT 0,
	`STAssValue` DOUBLE DEFAULT 0,
	`STRate` DOUBLE DEFAULT 0,
	`SBCRate` DOUBLE DEFAULT 0,
	`KKCRate` DOUBLE DEFAULT 0,
	`STCessRate` DOUBLE DEFAULT 0,
	`STHECessRate` DOUBLE DEFAULT 0
);
CREATE INDEX STDET_01 ON `STDet` (`VchCode`);




-- TDS definition

-- Drop table

-- DROP TABLE TDS;

CREATE TABLE TDS (
	`Method` SMALLINT DEFAULT 0,
	`RefNo` VARCHAR(25),
	`RefCode` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`EntryDate` TIMESTAMP DEFAULT '0',
	`DateOfCredit` TIMESTAMP DEFAULT '0',
	`VchAmt` DOUBLE DEFAULT 0,
	`TDSRate` DOUBLE DEFAULT 0,
	`TDSAmt` DOUBLE DEFAULT 0,
	`SurchargeRate` DOUBLE DEFAULT 0,
	`SurchargeAmt` DOUBLE DEFAULT 0,
	`CessRate` DOUBLE DEFAULT 0,
	`CessAmt` DOUBLE DEFAULT 0,
	`SHECessRate` DOUBLE DEFAULT 0,
	`SHECessAmt` DOUBLE DEFAULT 0,
	`Interest` DOUBLE DEFAULT 0,
	`OtherAmt` DOUBLE DEFAULT 0,
	`LowerRate` BOOLEAN DEFAULT false,
	`Reason` VARCHAR(20),
	`ChallanNo` VARCHAR(20),
	`ChequeNo` VARCHAR(20),
	`ChequeDate` TIMESTAMP DEFAULT '0',
	`Quarter` SMALLINT DEFAULT 0,
	`RecType` SMALLINT DEFAULT 0
);
CREATE INDEX TDS_01 ON TDS (`MasterCode2`,`Method`,`EntryDate`,`VchCode`);
CREATE INDEX TDS_02 ON TDS (`MasterCode1`,`Method`,`RefNo`);
CREATE INDEX TDS_03 ON TDS (`VchCode`,`MasterCode1`,`SrNo`);
CREATE INDEX TDS_04 ON TDS (`RefCode`,`Method`);
CREATE INDEX TDS_05 ON TDS (`RecType`);





-- `TradingExcise` definition

-- Drop table

-- DROP TABLE `TradingExcise`;

CREATE TABLE `TradingExcise` (
	`RefCode` INTEGER DEFAULT 0,
	`Stamp` INTEGER DEFAULT 0,
	`Method` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`RefNo` VARCHAR(25),
	`PartyCode` INTEGER DEFAULT 0,
	`VchNo` VARCHAR(25),
	`Date` TIMESTAMP DEFAULT '0',
	`ItemCode` INTEGER DEFAULT 0,
	`Qty` DOUBLE DEFAULT 0,
	`Balance` DOUBLE DEFAULT 0,
	`Status` SMALLINT DEFAULT 0,
	`AssValue` DOUBLE DEFAULT 0,
	`DutyRate` DOUBLE DEFAULT 0,
	`DutyType` SMALLINT DEFAULT 0,
	`DutyAmt` DOUBLE DEFAULT 0,
	`DutyRate1` DOUBLE DEFAULT 0,
	`DutyType1` SMALLINT DEFAULT 0,
	`DutyAmt1` DOUBLE DEFAULT 0,
	`DutyRate2` DOUBLE DEFAULT 0,
	`DutyType2` SMALLINT DEFAULT 0,
	`DutyAmt2` DOUBLE DEFAULT 0,
	`DutyRate3` DOUBLE DEFAULT 0,
	`DutyType3` SMALLINT DEFAULT 0,
	`DutyAmt3` DOUBLE DEFAULT 0,
	`MfrQty` DOUBLE DEFAULT 0,
	`MfrCode` INTEGER DEFAULT 0,
	`MfrBillNo` VARCHAR(25),
	`MfrBillDate` TIMESTAMP DEFAULT '0',
	`RG23DPageNo` VARCHAR(25),
	`RG23DSrNo` VARCHAR(25),
	`AutoRG23DPageNo` INTEGER DEFAULT 0,
	`AutoRG23DSrNo` INTEGER DEFAULT 0,
	`SuppRG23DPageNo` VARCHAR(25),
	`SuppRG23DSrNo` VARCHAR(25),
	`MCCode` INTEGER DEFAULT 0,
	`SuppAssValue` DOUBLE DEFAULT 0,
	`SuppDutyAmt` DOUBLE DEFAULT 0,
	`SuppDutyAmt1` DOUBLE DEFAULT 0,
	`SuppDutyAmt2` DOUBLE DEFAULT 0,
	`SuppDutyAmt3` DOUBLE DEFAULT 0,
	`CarryRefZeroQty` BOOLEAN DEFAULT false,
	`MfrInvoicePrepDateTime` VARCHAR(25),
	`MfrGoodsRemovalDateTime` VARCHAR(25),
	`ActualSuppAssValue` DOUBLE DEFAULT 0,
	`ActualSuppDutyAmt` DOUBLE DEFAULT 0,
	`ActualSuppDutyAmt1` DOUBLE DEFAULT 0,
	`ActualSuppDutyAmt2` DOUBLE DEFAULT 0,
	`ActualSuppDutyAmt3` DOUBLE DEFAULT 0,
	`ActualSuppQty` DOUBLE DEFAULT 0,
	`SuppOrgDetailsSpecified` BOOLEAN DEFAULT false
);
CREATE INDEX TRADINGEXCISE_01 ON `TradingExcise` (`RefCode`,`Method`,`Date`,`VchType`,`VchNo`,`VchCode`);
CREATE INDEX TRADINGEXCISE_02 ON `TradingExcise` (`ItemCode`,`Method`,`Status`);
CREATE INDEX TRADINGEXCISE_03 ON `TradingExcise` (`ItemCode`,`Method`,`RefNo`);
CREATE INDEX TRADINGEXCISE_04 ON `TradingExcise` (`VchCode`,`ItemCode`,`SrNo`);
CREATE INDEX TRADINGEXCISE_05 ON `TradingExcise` (`VchCode`,`ItemCode`,`RefNo`);
CREATE INDEX TRADINGEXCISE_06 ON `TradingExcise` (`MCCode`,`ItemCode`,`Method`,`Status`);
CREATE INDEX TRADINGEXCISE_07 ON `TradingExcise` (`MCCode`,`ItemCode`,`Method`,`RefNo`);
CREATE INDEX TRADINGEXCISE_08 ON `TradingExcise` (`VchCode`,`MCCode`,`ItemCode`,`SrNo`);
CREATE INDEX TRADINGEXCISE_09 ON `TradingExcise` (`VchCode`,`MCCode`,`ItemCode`,`RefNo`);
CREATE INDEX TRADINGEXCISE_10 ON `TradingExcise` (`AutoRG23DPageNo`,`AutoRG23DSrNo`);
CREATE INDEX TRADINGEXCISE_11 ON `TradingExcise` (`MCCode`,`AutoRG23DPageNo`,`AutoRG23DSrNo`);








-- `Tran1` definition

-- Drop table

-- DROP TABLE `Tran1`;

CREATE TABLE `Tran1` (
	`VchCode` INTEGER DEFAULT 0 NOT NULL,
	`VchType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`StockUpdationDate` TIMESTAMP DEFAULT '0',
	`Status` SMALLINT DEFAULT 0,
	`VchNo` VARCHAR(25),
	`VchSeriesCode` INTEGER DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`Stamp` INTEGER DEFAULT 0,
	`AutoVchNo` INTEGER DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	CM2 INTEGER DEFAULT 0,
	CM3 INTEGER DEFAULT 0,
	CM4 INTEGER DEFAULT 0,
	CM5 INTEGER DEFAULT 0,
	CM6 INTEGER DEFAULT 0,
	`FormRecAmt` DOUBLE DEFAULT 0,
	`FormIssAmt` DOUBLE DEFAULT 0,
	`CurConRate` DOUBLE DEFAULT 0,
	`VchAmtBaseCur` DOUBLE DEFAULT 0,
	`VchSalePurcAmt` DOUBLE DEFAULT 0,
	`ExciseApplicable` BOOLEAN DEFAULT false,
	`ExciseDocName` VARCHAR(20),
	`ExciseValue` DOUBLE DEFAULT 0,
	`ExciseType` SMALLINT DEFAULT 0,
	`ExcisableAmount` DOUBLE DEFAULT 0,
	`ExciseRate` DOUBLE DEFAULT 0,
	`OrgVchAmtBaseCur` DOUBLE DEFAULT 0,
	`TEApplicable` BOOLEAN DEFAULT false,
	`TDSApplicable` BOOLEAN DEFAULT false,
	`FormRecStatus` SMALLINT DEFAULT 0,
	`FormIssStatus` SMALLINT DEFAULT 0,
	`ChallanStatus` SMALLINT DEFAULT 0,
	`STApplicable` BOOLEAN DEFAULT false,
	`STType` SMALLINT DEFAULT 0,
	`DocPrinted` BOOLEAN DEFAULT false,
	`External` BOOLEAN DEFAULT false,
	`CreatedBy` VARCHAR(20),
	`CreationTime` TIMESTAMP DEFAULT '0',
	`AuthorisedBy` VARCHAR(20),
	`AuthorisationTime` TIMESTAMP DEFAULT '0',
	`ModifiedBy` VARCHAR(20),
	`ModificationTime` TIMESTAMP DEFAULT '0',
	`PriceCategory` SMALLINT DEFAULT 0,
	`VATInfo` BOOLEAN DEFAULT false,
	`POSEnabled` BOOLEAN DEFAULT false,
	`AutoGeneratedType` SMALLINT DEFAULT 0,
	`VchCancelled` BOOLEAN DEFAULT false,
	`BrokerageMode` SMALLINT DEFAULT 0,
	`Brokerage` DOUBLE DEFAULT 0,
	`BrokerageAmt` DOUBLE DEFAULT 0,
	`TranType` SMALLINT DEFAULT 0,
	`FreeQtyUsed` BOOLEAN DEFAULT false,
	`Cancelled` BOOLEAN DEFAULT false,
	D1 DOUBLE DEFAULT 0,
	`ApprovalStatus` SMALLINT DEFAULT 0,
	`SyncStatus` BOOLEAN DEFAULT false,
	`Source` SMALLINT DEFAULT 0,
	`AuditStatus` SMALLINT DEFAULT 0,
	`ExtraExpense` DOUBLE DEFAULT 0,
	`ExtraExpenseNar1` VARCHAR(40),
	`ExtraExpenseNar2` VARCHAR(40),
	`c1` VARCHAR(255),
	`Date1` TIMESTAMP DEFAULT '0',
	`Date2` TIMESTAMP DEFAULT '0',
	I1 SMALLINT DEFAULT 0,
	I2 SMALLINT DEFAULT 0,
	I3 SMALLINT DEFAULT 0,
	I4 SMALLINT DEFAULT 0,
	I5 SMALLINT DEFAULT 0,
	I6 SMALLINT DEFAULT 0,
	I7 SMALLINT DEFAULT 0,
	I8 SMALLINT DEFAULT 0,
	I9 SMALLINT DEFAULT 0,
	I10 SMALLINT DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	TPF1 BOOLEAN DEFAULT false,
	TPF2 BOOLEAN DEFAULT false,
	`RejectionStatus` SMALLINT DEFAULT 0,
	L1 INTEGER DEFAULT 0,
	`SourceDet` VARCHAR(255),
	`NepaliDate` VARCHAR(255),
	`NepaliFY` VARCHAR(255),
	CM7 INTEGER DEFAULT 0,
	`OldIdentity` VARCHAR(16777216),
	CONSTRAINT SYS_PK_12199 PRIMARY KEY (`VchCode`)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12199_12200 ON `Tran1` (`VchCode`);
CREATE INDEX TRAN1_02 ON `Tran1` (`MasterCode1`);
CREATE INDEX TRAN1_03 ON `Tran1` (`MasterCode2`);
CREATE INDEX TRAN1_19 ON `Tran1` (CM5);
CREATE INDEX TRAN1_21 ON `Tran1` (`Date`);
CREATE INDEX TRAN1_22 ON `Tran1` (`VchType`);
CREATE INDEX TRAN1_23 ON `Tran1` (`VchNo`);
CREATE INDEX TRAN1_24 ON `Tran1` (`VchSeriesCode`);
CREATE INDEX TRAN1_26 ON `Tran1` (CM1);
CREATE INDEX TRAN1_27 ON `Tran1` (CM2);
CREATE INDEX TRAN1_28 ON `Tran1` (CM3);
CREATE INDEX TRAN1_29 ON `Tran1` (CM4);
CREATE INDEX TRAN1_30 ON `Tran1` (`AutoGeneratedType`);
CREATE INDEX TRAN1_31 ON `Tran1` (`StockUpdationDate`);
CREATE INDEX TRAN1_32 ON `Tran1` (`SyncStatus`);
CREATE INDEX TRAN1_33 ON `Tran1` (`Source`);
CREATE INDEX TRAN1_34 ON `Tran1` (CM7);
CREATE INDEX TRAN1_35 ON `Tran1` (`TranType`);
CREATE INDEX TRAN1_62 ON `Tran1` (`VchType`,`Date`);
CREATE INDEX TRAN1_63 ON `Tran1` (`VchSeriesCode`,`AutoVchNo`);
CREATE INDEX TRAN1_64 ON `Tran1` (`VchSeriesCode`,`Date`,`VchNo`);
CREATE INDEX TRAN1_81 ON `Tran1` (`VchCode`);
CREATE INDEX TRAN1_82 ON `Tran1` (`Date`);




-- `Tran2` definition

-- Drop table

-- DROP TABLE `Tran2`;

CREATE TABLE `Tran2` (
	`RecType` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`VchNo` VARCHAR(25),
	`VchSeriesCode` INTEGER DEFAULT 0,
	`Value1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	`Value3` DOUBLE DEFAULT 0,
	`Balance1` DOUBLE DEFAULT 0,
	`Balance2` DOUBLE DEFAULT 0,
	`Balance3` DOUBLE DEFAULT 0,
	`ItemBal1` DOUBLE DEFAULT 0,
	`ItemBal2` DOUBLE DEFAULT 0,
	`ItemBal3` DOUBLE DEFAULT 0,
	`CashFlow` DOUBLE DEFAULT 0,
	`ShortNar` VARCHAR(40),
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	D7 DOUBLE DEFAULT 0,
	D8 DOUBLE DEFAULT 0,
	D9 DOUBLE DEFAULT 0,
	D10 DOUBLE DEFAULT 0,
	D11 DOUBLE DEFAULT 0,
	D12 DOUBLE DEFAULT 0,
	D13 DOUBLE DEFAULT 0,
	D14 DOUBLE DEFAULT 0,
	D15 DOUBLE DEFAULT 0,
	D16 DOUBLE DEFAULT 0,
	D17 DOUBLE DEFAULT 0,
	D18 DOUBLE DEFAULT 0,
	D19 DOUBLE DEFAULT 0,
	D20 DOUBLE DEFAULT 0,
	D21 DOUBLE DEFAULT 0,
	D22 DOUBLE DEFAULT 0,
	D23 DOUBLE DEFAULT 0,
	D24 DOUBLE DEFAULT 0,
	D25 DOUBLE DEFAULT 0,
	D26 DOUBLE DEFAULT 0,
	D27 DOUBLE DEFAULT 0,
	D28 DOUBLE DEFAULT 0,
	D29 DOUBLE DEFAULT 0,
	D30 DOUBLE DEFAULT 0,
	D31 DOUBLE DEFAULT 0,
	D32 DOUBLE DEFAULT 0,
	I1 SMALLINT DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	CM2 INTEGER DEFAULT 0,
	CM3 INTEGER DEFAULT 0,
	CM4 INTEGER DEFAULT 0,
	CM5 INTEGER DEFAULT 0,
	CM6 INTEGER DEFAULT 0,
	CM7 INTEGER DEFAULT 0,
	CM8 INTEGER DEFAULT 0,
	CM9 INTEGER DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	B2 BOOLEAN DEFAULT false,
	B3 BOOLEAN DEFAULT false,
	B4 BOOLEAN DEFAULT false,
	B5 BOOLEAN DEFAULT false,
	B6 BOOLEAN DEFAULT false,
	B7 BOOLEAN DEFAULT false,
	B8 BOOLEAN DEFAULT false,
	`ClrDate` TIMESTAMP DEFAULT '0',
	`PriceCategory` SMALLINT DEFAULT 0,
	`CFMode` SMALLINT DEFAULT 0,
	C1 VARCHAR(255),
	C2 VARCHAR(255),
	C3 VARCHAR(255),
	`TranType` SMALLINT DEFAULT 0,
	`IsReturnQty` BOOLEAN DEFAULT false,
	`ReconStatus` BOOLEAN DEFAULT false,
	I2 SMALLINT DEFAULT 0,
	I3 SMALLINT DEFAULT 0,
	I4 SMALLINT DEFAULT 0,
	I5 SMALLINT DEFAULT 0,
	I6 SMALLINT DEFAULT 0,
	I7 SMALLINT DEFAULT 0,
	I8 SMALLINT DEFAULT 0,
	I9 SMALLINT DEFAULT 0,
	I10 SMALLINT DEFAULT 0,
	`TrackingStatus` SMALLINT DEFAULT 0,
	`TrackingNo` VARCHAR(255)
);
CREATE INDEX TRAN2_01 ON `Tran2` (`MasterCode1`);
CREATE INDEX TRAN2_02 ON `Tran2` (`MasterCode2`);
CREATE INDEX TRAN2_03 ON `Tran2` (CM1);
CREATE INDEX TRAN2_08 ON `Tran2` (`VchCode`);
CREATE INDEX TRAN2_31 ON `Tran2` (`RecType`);
CREATE INDEX TRAN2_32 ON `Tran2` (`VchType`);
CREATE INDEX TRAN2_33 ON `Tran2` (`VchNo`);
CREATE INDEX TRAN2_34 ON `Tran2` (`Date`);
CREATE INDEX TRAN2_36 ON `Tran2` (`VchSeriesCode`);
CREATE INDEX TRAN2_38 ON `Tran2` (CM2);
CREATE INDEX TRAN2_39 ON `Tran2` (CM3);
CREATE INDEX TRAN2_40 ON `Tran2` (CM4);
CREATE INDEX TRAN2_41 ON `Tran2` (CM5);
CREATE INDEX TRAN2_42 ON `Tran2` (D18);
CREATE INDEX TRAN2_43 ON `Tran2` (D26);
CREATE INDEX TRAN2_44 ON `Tran2` (CM6);
CREATE INDEX TRAN2_45 ON `Tran2` (`IsReturnQty`);
CREATE INDEX TRAN2_46 ON `Tran2` (C3);
CREATE INDEX TRAN2_47 ON `Tran2` (`TrackingNo`);
CREATE INDEX TRAN2_48 ON `Tran2` (`TrackingStatus`);
CREATE INDEX TRAN2_49 ON `Tran2` (`TranType`);
CREATE INDEX TRAN2_50 ON `Tran2` (CM7);
CREATE INDEX TRAN2_51 ON `Tran2` (CM8);
CREATE INDEX TRAN2_52 ON `Tran2` (CM9);
CREATE INDEX TRAN2_81 ON `Tran2` (`MasterCode2`);





-- `Tran3` definition

-- Drop table

-- DROP TABLE `Tran3`;

CREATE TABLE `Tran3` (
	`RefCode` INTEGER DEFAULT 0,
	`RecType` SMALLINT DEFAULT 0,
	`Method` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`RefGrp` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`DueDate` TIMESTAMP DEFAULT '0',
	`No` VARCHAR(25),
	`Status` SMALLINT DEFAULT 0,
	`Type` SMALLINT DEFAULT 0,
	`BrokerCode` INTEGER DEFAULT 0,
	`Value1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	`Value3` DOUBLE DEFAULT 0,
	`Balance1` DOUBLE DEFAULT 0,
	`Balance2` DOUBLE DEFAULT 0,
	`Balance3` DOUBLE DEFAULT 0,
	`ItemSrNo` SMALLINT DEFAULT 0,
	`MfgDate` TIMESTAMP DEFAULT '0',
	`TranType` SMALLINT DEFAULT 0,
	CM1 INTEGER DEFAULT 0,
	CM2 INTEGER DEFAULT 0,
	`ApprovalStatus` SMALLINT DEFAULT 0,
	`NewRefAmount` DOUBLE DEFAULT 0,
	`Narration` VARCHAR(255),
	`BranchCode` INTEGER DEFAULT 0
);
CREATE INDEX TRAN3_04 ON `Tran3` (`MasterCode1`);
CREATE INDEX TRAN3_05 ON `Tran3` (`MasterCode2`);
CREATE INDEX TRAN3_09 ON `Tran3` (`RefGrp`);
CREATE INDEX TRAN3_20 ON `Tran3` (`SrNo`);
CREATE INDEX TRAN3_21 ON `Tran3` (`Date`);
CREATE INDEX TRAN3_22 ON `Tran3` (`VchType`);
CREATE INDEX TRAN3_23 ON `Tran3` (`VchCode`);
CREATE INDEX TRAN3_24 ON `Tran3` (`RefCode`);
CREATE INDEX TRAN3_25 ON `Tran3` (`RecType`);
CREATE INDEX TRAN3_26 ON `Tran3` (`Type`);
CREATE INDEX TRAN3_27 ON `Tran3` (`Method`);
CREATE INDEX TRAN3_28 ON `Tran3` (`DueDate`);
CREATE INDEX TRAN3_29 ON `Tran3` (`No`);
CREATE INDEX TRAN3_31 ON `Tran3` (`Status`);
CREATE INDEX TRAN3_32 ON `Tran3` (`ApprovalStatus`);
CREATE INDEX TRAN3_33 ON `Tran3` (`TranType`);
CREATE INDEX TRAN3_34 ON `Tran3` (`Value1`);
CREATE INDEX TRAN3_61 ON `Tran3` (`RecType`,`MasterCode1`,`MasterCode2`,`No`);
CREATE INDEX TRAN3_62 ON `Tran3` (`RefCode`,`Date`);
CREATE INDEX TRAN3_81 ON `Tran3` (`RefCode`);






-- `Tran4` definition

-- Drop table

-- DROP TABLE `Tran4`;

CREATE TABLE `Tran4` (
	`SrNo` INTEGER DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	`BranchCode` INTEGER DEFAULT 0,
	`RecType` SMALLINT DEFAULT 0
);
CREATE INDEX TRAN4_01 ON `Tran4` (`MasterCode1`,`MasterCode2`);
CREATE INDEX TRAN4_02 ON `Tran4` (`MasterCode1`,`SrNo`);
CREATE INDEX TRAN4_03 ON `Tran4` (`MasterCode2`);
CREATE INDEX TRAN4_06 ON `Tran4` (`BranchCode`);
CREATE INDEX TRAN4_07 ON `Tran4` (`RecType`);



-- `Tran5` definition

-- Drop table

-- DROP TABLE `Tran5`;

CREATE TABLE `Tran5` (
	`VchCode` INTEGER DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`VchNo` VARCHAR(25),
	`VchSeriesCode` INTEGER DEFAULT 0,
	`Value1` DOUBLE DEFAULT 0,
	`Value2` DOUBLE DEFAULT 0,
	`Balance1` DOUBLE DEFAULT 0,
	`Balance2` DOUBLE DEFAULT 0,
	`TranType` SMALLINT DEFAULT 0,
	`ShortNar` VARCHAR(40),
	`TrackingNo` VARCHAR(255),
	`TrackingStatus` SMALLINT DEFAULT 0
);
CREATE INDEX TRAN5_01 ON `Tran5` (`MasterCode1`,`Date`,`VchType`,`VchNo`,`VchCode`);
CREATE INDEX TRAN5_02 ON `Tran5` (`VchCode`,`MasterCode1`,`TranType`,`SrNo`);
CREATE INDEX TRAN5_03 ON `Tran5` (`VchCode`,`TranType`,`SrNo`);
CREATE INDEX TRAN5_04 ON `Tran5` (`MasterCode1`,`MasterCode2`,`Date`,`VchNo`,`VchCode`);
CREATE INDEX TRAN5_05 ON `Tran5` (`MasterCode1`,`VchType`,`Date`,`VchNo`,`VchCode`);
CREATE INDEX TRAN5_06 ON `Tran5` (`MasterCode1`,`MasterCode2`,`Value1`,`Date`);
CREATE INDEX TRAN5_07 ON `Tran5` (`MasterCode2`,`MasterCode1`,`Value1`,`Date`);
CREATE INDEX TRAN5_08 ON `Tran5` (`MasterCode1`,`VchType`,`Value1`,`Date`);
CREATE INDEX TRAN5_09 ON `Tran5` (`VchType`,`MasterCode1`,`Value1`,`Date`);
CREATE INDEX TRAN5_10 ON `Tran5` (`VchCode`,`MasterCode2`,`SrNo`);





-- `Tran6` definition

-- Drop table

-- DROP TABLE `Tran6`;

CREATE TABLE `Tran6` (
	`SrNo` INTEGER DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`StockType` SMALLINT DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0
);
CREATE INDEX TRAN6_01 ON `Tran6` (`MasterCode1`,`MasterCode2`,`StockType`);
CREATE INDEX TRAN6_02 ON `Tran6` (`MasterCode1`,`StockType`,`SrNo`);
CREATE INDEX TRAN6_03 ON `Tran6` (`MasterCode2`);





-- `Tran7` definition

-- Drop table

-- DROP TABLE `Tran7`;

CREATE TABLE `Tran7` (
	`MasterCode` INTEGER DEFAULT 0
);
CREATE INDEX TRAN7_01 ON `Tran7` (`MasterCode`);



-- `Tran8` definition

-- Drop table

-- DROP TABLE `Tran8`;

CREATE TABLE `Tran8` (
	`VchCode` INTEGER DEFAULT 0 NOT NULL,
	`VchType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`FormRecDate` TIMESTAMP DEFAULT '0',
	`FormNo` VARCHAR(25),
	`PartyCode` INTEGER DEFAULT 0,
	`FormCode` INTEGER DEFAULT 0,
	`Stamp` INTEGER DEFAULT 0,
	`Nar1` VARCHAR(94),
	`AutoVchNo` INTEGER DEFAULT 0,
	`CreatedBy` VARCHAR(20),
	`CreationTime` TIMESTAMP DEFAULT '0',
	`AuthorisedBy` VARCHAR(20),
	`AuthorisationTime` TIMESTAMP DEFAULT '0',
	`ModifiedBy` VARCHAR(20),
	`ModificationTime` TIMESTAMP DEFAULT '0',
	`StateCode` SMALLINT DEFAULT 0,
	`Series` VARCHAR(255),
	`IssuingOffice` VARCHAR(255),
	CONSTRAINT SYS_PK_12204 PRIMARY KEY (`VchCode`)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12204_12205 ON `Tran8` (`VchCode`);
CREATE INDEX TRAN8_02 ON `Tran8` (`VchType`,`Date`,`FormNo`,`VchCode`);
CREATE INDEX TRAN8_03 ON `Tran8` (`VchType`,`FormNo`);




-- `Tran9` definition

-- Drop table

-- DROP TABLE `Tran9`;

CREATE TABLE `Tran9` (
	`VchCode` INTEGER DEFAULT 0,
	`PartyCode` INTEGER DEFAULT 0,
	`FormCode` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`FormNo` VARCHAR(25),
	`BillCode` INTEGER DEFAULT 0,
	`Amount` DOUBLE DEFAULT 0
);
CREATE INDEX TRAN9_01 ON `Tran9` (`VchCode`,`SrNo`);
CREATE INDEX TRAN9_02 ON `Tran9` (`VchType`,`BillCode`);





-- `Tran10` definition

-- Drop table

-- DROP TABLE `Tran10`;

CREATE TABLE `Tran10` (
	`RecType` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	I1 SMALLINT DEFAULT 0,
	I2 SMALLINT DEFAULT 0,
	I3 SMALLINT DEFAULT 0,
	I4 SMALLINT DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`Mastercode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	D1 DOUBLE DEFAULT 0,
	D2 DOUBLE DEFAULT 0,
	D3 DOUBLE DEFAULT 0,
	D4 DOUBLE DEFAULT 0,
	D5 DOUBLE DEFAULT 0,
	D6 DOUBLE DEFAULT 0,
	D7 DOUBLE DEFAULT 0,
	D8 DOUBLE DEFAULT 0,
	D9 DOUBLE DEFAULT 0,
	D10 DOUBLE DEFAULT 0,
	C1 VARCHAR(255),
	C2 VARCHAR(255),
	C3 VARCHAR(255),
	C4 VARCHAR(255),
	C5 VARCHAR(255),
	C6 VARCHAR(255),
	C7 VARCHAR(255),
	C8 VARCHAR(255),
	C9 VARCHAR(255),
	C10 VARCHAR(255),
	`Date` TIMESTAMP DEFAULT '0',
	`MasterCode3` INTEGER DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	B2 BOOLEAN DEFAULT false,
	B3 BOOLEAN DEFAULT false
);
CREATE INDEX TRAN10_01 ON `Tran10` (`Mastercode1`,`MasterCode2`);
CREATE INDEX TRAN10_02 ON `Tran10` (`MasterCode2`);
CREATE INDEX TRAN10_03 ON `Tran10` (`VchType`,`RecType`,`Mastercode1`,`SrNo`);
CREATE INDEX TRAN10_04 ON `Tran10` (C1);
CREATE INDEX TRAN10_05 ON `Tran10` (`MasterCode3`);
CREATE INDEX TRAN10_06 ON `Tran10` (`Date`);
CREATE INDEX TRAN10_07 ON `Tran10` (`Date`);
CREATE INDEX TRAN10_08 ON `Tran10` (`RecType`);


-- `Tran11` definition

-- Drop table

-- DROP TABLE `Tran11`;

CREATE TABLE `Tran11` (
	`RecType` SMALLINT DEFAULT 0,
	`TranType` SMALLINT DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`MasterCode1` INTEGER DEFAULT 0,
	`MasterCode2` INTEGER DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`VchNo` VARCHAR(25),
	`VchSeriesCode` INTEGER DEFAULT 0,
	`ShortNar` VARCHAR(40),
	I1 SMALLINT DEFAULT 0,
	I2 SMALLINT DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	CM1 INTEGER DEFAULT 0,
	CM2 INTEGER DEFAULT 0,
	CM3 INTEGER DEFAULT 0,
	CM4 INTEGER DEFAULT 0,
	CM5 INTEGER DEFAULT 0,
	CM6 INTEGER DEFAULT 0,
	CM7 INTEGER DEFAULT 0,
	CM8 INTEGER DEFAULT 0,
	`Date1` TIMESTAMP DEFAULT '0',
	`Date2` TIMESTAMP DEFAULT '0',
	`Date3` TIMESTAMP DEFAULT '0',
	`Date4` TIMESTAMP DEFAULT '0',
	`Date5` TIMESTAMP DEFAULT '0',
	C1 VARCHAR(255),
	C2 VARCHAR(255),
	M1 VARCHAR(16777216),
	M2 VARCHAR(16777216)
);
CREATE INDEX TRAN11_01 ON `Tran11` (`MasterCode1`);
CREATE INDEX TRAN11_02 ON `Tran11` (C1);
CREATE INDEX TRAN11_03 ON `Tran11` (`Date`);
CREATE INDEX TRAN11_04 ON `Tran11` (CM3);
CREATE INDEX TRAN11_05 ON `Tran11` (`TranType`);
CREATE INDEX TRAN11_06 ON `Tran11` (`VchType`);
CREATE INDEX TRAN11_07 ON `Tran11` (`RecType`);




-- `Tran12` definition

-- Drop table

-- DROP TABLE `Tran12`;

CREATE TABLE `Tran12` (
	`VchCode` INTEGER DEFAULT 0,
	`Date` TIMESTAMP DEFAULT '0',
	`UserName` VARCHAR(40)
);
CREATE INDEX TRAN12_01 ON `Tran12` (`VchCode`);
CREATE INDEX TRAN12_02 ON `Tran12` (`Date`);




-- `VATInfo` definition

-- Drop table

-- DROP TABLE `VATInfo`;

CREATE TABLE `VATInfo` (
	`Date` TIMESTAMP DEFAULT '0',
	`Amount` DOUBLE DEFAULT 0,
	`RecType` SMALLINT DEFAULT 0,
	`Type` SMALLINT DEFAULT 0,
	`SrNo` SMALLINT DEFAULT 0,
	`Description` VARCHAR(80),
	`VchCode` INTEGER DEFAULT 0,
	`ChallanNo` VARCHAR(40),
	`ChallanDate` TIMESTAMP DEFAULT '0',
	`ChequeNo` VARCHAR(10),
	`ChequeDate` TIMESTAMP DEFAULT '0',
	`BankName` VARCHAR(40),
	`BankCode` VARCHAR(20),
	`Interest` DOUBLE DEFAULT 0,
	`Penalty` DOUBLE DEFAULT 0,
	`BankAcType` VARCHAR(10),
	`BankAcNo` VARCHAR(15),
	`SurchargeAmt` DOUBLE DEFAULT 0,
	`SaleAmt` DOUBLE DEFAULT 0,
	`TaxPercent` DOUBLE DEFAULT 0,
	`SurchargePercent` DOUBLE DEFAULT 0
);
CREATE INDEX VATINFO_01 ON `VATInfo` (`Date`);
CREATE INDEX VATINFO_02 ON `VATInfo` (`VchCode`);



-- `VchOtherInfo` definition

-- Drop table

-- DROP TABLE `VchOtherInfo`;

CREATE TABLE `VchOtherInfo` (
	`VchCode` INTEGER DEFAULT 0,
	OF1 VARCHAR(30),
	OF2 VARCHAR(30),
	OF3 VARCHAR(30),
	OF4 VARCHAR(30),
	OF5 VARCHAR(30),
	OF6 VARCHAR(30),
	OF7 VARCHAR(30),
	OF8 VARCHAR(30),
	OF9 VARCHAR(30),
	OF10 VARCHAR(30),
	`Transport` VARCHAR(30),
	`Station` VARCHAR(30),
	`GrNo` VARCHAR(30),
	`VehicleNo` VARCHAR(30),
	`ItemDesc` VARCHAR(20),
	`Form31No` VARCHAR(20),
	`Form31IssuedOn` VARCHAR(20),
	`TotalQty` VARCHAR(20),
	`PurchaseBillNo` VARCHAR(25),
	`PurchaseBillDate` VARCHAR(20),
	`Narration1` VARCHAR(94),
	`Narration2` VARCHAR(94),
	`InvoicePrepTime` VARCHAR(25),
	`GoodsRemovalTime` VARCHAR(25),
	`GrDate` TIMESTAMP DEFAULT '0',
	`VchNotes` VARCHAR(16777216),
	I1 SMALLINT DEFAULT 0,
	OF11 VARCHAR(30),
	OF12 VARCHAR(30),
	OF13 VARCHAR(30),
	OF14 VARCHAR(30),
	OF15 VARCHAR(30),
	OF16 VARCHAR(30),
	OF17 VARCHAR(30),
	OF18 VARCHAR(30),
	OF19 VARCHAR(30),
	OF20 VARCHAR(30)
);
CREATE INDEX VCHOTHERINFO_01 ON `VchOtherInfo` (`VchCode`);




-- `VchTemplate` definition

-- Drop table

-- DROP TABLE `VchTemplate`;

CREATE TABLE `VchTemplate` (
	`VchCode` INTEGER DEFAULT 0,
	`TemplateName` VARCHAR(20)
);
CREATE INDEX VCHTEMPLATE_01 ON `VchTemplate` (`VchCode`);
CREATE INDEX VCHTEMPLATE_02 ON `VchTemplate` (`TemplateName`);




-- `VchTempTagging` definition

-- Drop table

-- DROP TABLE `VchTempTagging`;

CREATE TABLE `VchTempTagging` (
	`MasterCode` INTEGER DEFAULT 0,
	`VchType` SMALLINT DEFAULT 0,
	`TemplateVchCode` INTEGER DEFAULT 0,
	B1 BOOLEAN DEFAULT false,
	B2 BOOLEAN DEFAULT false,
	B3 BOOLEAN DEFAULT false,
	B4 BOOLEAN DEFAULT false,
	B5 BOOLEAN DEFAULT false,
	I1 SMALLINT DEFAULT 0,
	I2 SMALLINT DEFAULT 0,
	`MasterType` SMALLINT DEFAULT 0
);
CREATE INDEX VCHTEMPTAGGING_01 ON `VchTempTagging` (`MasterCode`,`VchType`);
CREATE INDEX VCHTEMPTAGGING_02 ON `VchTempTagging` (`MasterType`,`VchType`);





-- `VchVATSum` definition

-- Drop table

-- DROP TABLE `VchVATSum`;

CREATE TABLE `VchVATSum` (
	`VchCode` INTEGER DEFAULT 0,
	`SaleAmt` DOUBLE DEFAULT 0,
	`TaxRate` DOUBLE DEFAULT 0,
	`TaxAmt` DOUBLE DEFAULT 0,
	`SurchargeRate` DOUBLE DEFAULT 0,
	`SurchargeAmt` DOUBLE DEFAULT 0,
	`TaxType` SMALLINT DEFAULT 0,
	`ActualSaleAmt` DOUBLE DEFAULT 0,
	`TaxOnMRP` BOOLEAN DEFAULT false
);
CREATE INDEX VCHVATSUM_01 ON `VchVATSum` (`VchCode`);




-- `VchVATSumItemWise` definition

-- Drop table

-- DROP TABLE `VchVATSumItemWise`;

CREATE TABLE `VchVATSumItemWise` (
	`ItemSrNo` SMALLINT DEFAULT 0,
	`ItemCode` INTEGER DEFAULT 0,
	`VchCode` INTEGER DEFAULT 0,
	`SaleAmt` DOUBLE DEFAULT 0,
	`TaxRate` DOUBLE DEFAULT 0,
	`TaxAmt` DOUBLE DEFAULT 0,
	`SurchargeRate` DOUBLE DEFAULT 0,
	`SurchargeAmt` DOUBLE DEFAULT 0,
	`TaxType` SMALLINT DEFAULT 0,
	`ActualSaleAmt` DOUBLE DEFAULT 0,
	`TaxOnMRP` BOOLEAN DEFAULT false
);
CREATE INDEX VCHVATSUMITEMWISE_01 ON `VchVATSumItemWise` (`VchCode`,`ItemSrNo`);
CREATE INDEX VCHVATSUMITEMWISE_02 ON `VchVATSumItemWise` (`ItemCode`);






"""

new_string = convert_string.replace("BOOLEAN", "boolean")
new_string = new_string.replace("SMALLINT", "smallint")
new_string = new_string.replace("VARCHAR", "text")
new_string = new_string.replace("INTEGER", "integer")
new_string = new_string.replace("DOUBLE", "float")
new_string = new_string.replace("TIMESTAMP", "timestamp")

new_string = new_string.replace("`", "")



# for each line in new string
for line in new_string.splitlines():
    # for each line in new string if timestamp exists then remove substring after timestamp except ","
    if "timestamp" in line:
        print(line)
        line2 = line[:line.find("timestamp")+10]+line[line.find(","):]
        print(line)
        # replace with line
        new_string = new_string.replace(line, line2)



# replace text(16777216) with text
new_string = re.sub(r'text\(\d+\)', 'text', new_string)

# print new string



print(new_string)

# save to text file
with open("new_string_2.txt", "w") as text_file:
    text_file.write(new_string)













# BOOLEAN
# SMALLINT
# VARCHAR,
# INTEGER
# DOUBLE
# TIMESTAMP

# replace them with below into in string
# 	float,
# 	boolean,
# 	smallint,
# 	text,
# 	integer,
# 	timestamp
